{
  "hash": "a7ac4df7e37f0ee3e5585c073d4c4347",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Usar distribuições de atraso na análise'\n---\n\n::: {.callout-note title=\"Perguntas\"}\n\n- Como reutilizar atrasos armazenados na biblioteca `{epiparameter}` com o meu pipeline de análise existente?\n\n:::\n\n::: {.callout-tip title=\"Objetivos\"}\n\n- Usar funções de distribuição com distribuições contínuas e discretas armazenadas como objetos `<epiparameter>`.\n- Converter uma distribuição contínua em discreta com o `{epiparameter}`.\n- Conectar as saídas do `{epiparameter}` com as entradas do `{EpiNow2}`.\n\n:::\n\n::: {.callout-important title=\"Pré-requisitos\"}\n\n## Pré-requisitos\n\n- Concluir o tutorial [Acessar distribuições epidemiológicas de atraso](01-acessar-atrasos.qmd)\n- Concluir o tutorial [Quantificar a transmissibilidade](02-quantificar-transmissibilidade.qmd)\n\nEste episódio requer que você tenha familiaridade com:\n\n**Ciência de dados**: Programação básica em R.\n\n**Estatística**: Distribuições de probabilidade.\n\n**Teoria epidemiológica**: Parâmetros epidemiológicos, períodos de tempo, número de reprodução efetivo.\n\n:::\n\n## Introdução\n\n<!-- to activate for EpiNow2@dist-interfase\n\n::: {.callout-note}\n\nSe escrevermos `[]` ao lado do último objeto criado, como em `covid_serialint_parameters[]`, dentro de `[]` podemos usar a\ntecla Tab <kbd>↹</kbd>\npara usar o [recurso de autocompletar código](https://support.posit.co/hc/en-us/articles/205273297-Code-Completion-in-the-RStudio-IDE) e ter acesso rápido a `covid_serialint_parameters[\"meanlog\"]` e `covid_serialint_parameters[\"sdlog\"]`. Convidamos você a experimentar isso nos blocos de código e no console do R!\n\n:::\n\n-->\n\nEste episódio integrará o conteúdo dos dois episódios anteriores. Vamos começar carregando os pacotes `{epiparameter}` e `{EpiNow2}`. Usaremos o pipe `%>%`, alguns verbos do `{dplyr}` e o `{ggplot2}`, então vamos chamar também o pacote `{tidyverse}`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(epiparameter)\nlibrary(EpiNow2)\nlibrary(tidyverse)\n```\n:::\n\n\nPara recapitular, aprendemos que o `{epiparameter}` nos ajuda a *escolher* um conjunto específico de parâmetros epidemiológicos da literatura, em vez de copiar/colar *à mão*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_serialint <-\n  epiparameter::epiparameter_db(\n    disease = \"covid\",\n    epi_name = \"serial\",\n    single_epiparameter = TRUE\n  )\n```\n:::\n\n\nAgora, temos um parâmetro epidemiológico que podemos usar em nossa análise! \nNo entanto, não podemos usar esse objeto _diretamente_ para a análise.\nPor exemplo, para quantificar a transmissão, frequentemente usamos a distribuição do intervalo serial como uma aproximação do tempo de geração. \nPara fazer isso, precisamos aplicar funções adicionais a um objeto `<epiparameter>` para \nextrair suas **estatísticas resumo** ou **parâmetros da distribuição**. \nEssas saídas podem então ser usadas como entradas para `EpiNow2::LogNormal()` ou `EpiNow2::Gamma()`,\nexatamente como fizemos no episódio anterior.\n\nNeste episódio, usaremos as **funções de distribuição** fornecidas pelo `{epiparameter}` para obter \nvalores descritivos como a mediana, o valor máximo (`max`), percentis ou quantis.\nEsse conjunto de funções pode operar sobre **qualquer distribuição** que possa ser incluída em um objeto `<epiparameter>`: \nGama, Weibull, Lognormal, Binomial Negativa, Geométrica e Poisson,\nque são as mais utilizadas na análise de surtos.\n\nVocê precisará dessas saídas nos próximos episódios para alimentar seus pipelines de análise — então vamos garantir que você se sinta confortável trabalhando com elas antes de prosseguir!\n\n::: {.callout-note title=\"Checklist\"}\n\n### Os dois-pontos duplos\n\nOs dois-pontos duplos `::` no R permitem chamar uma função específica de um pacote sem carregar o pacote inteiro no ambiente atual. \n\nPor exemplo, `dplyr::filter(data, condition)` usa `filter()` do pacote `{dplyr}`.\n\nIsso nos ajuda a lembrar as funções dos pacotes e a evitar conflitos de namespace ao especificar explicitamente a função de qual pacote usar quando múltiplos pacotes têm funções com o mesmo nome.\n\n:::\n\n## Funções de distribuição\n\nNo R, todas as distribuições estatísticas possuem funções para acessar o seguinte:\n\n- `density()`: função de **densidade** de probabilidade (PDF),\n- `cdf()`: função de distribuição acumulada (**CDF**),\n- `quantile()`: função de **quantil** e\n- `generate()`: valores **aleatórios** a partir da distribuição fornecida.\n\n::: {.callout-note title=\"Checklist\"}\n\n### Funções para a distribuição normal\n\nSe precisar, leia em detalhes sobre as [funções de probabilidade do R para a distribuição normal](https://web.archive.org/web/20240210121034/https://sakai.unc.edu/access/content/group/3d1eb92e-7848-4f55-90c3-7c72a54e7e43/public/docs/lectures/lecture13.htm#probfunc), cada uma de suas definições e identifique em qual parte de uma distribuição elas se localizam!\n\n![As quatro funções de probabilidade para a distribuição normal ([Jack Weiss, 2012](https://web.archive.org/web/20240210121034/https://sakai.unc.edu/access/content/group/3d1eb92e-7848-4f55-90c3-7c72a54e7e43/public/docs/lectures/lecture13.htm#probfunc))](../img/fig5a-normaldistribution.png)\n\n:::\n\nSe você consultar `?stats::Distributions`, cada tipo de distribuição possui um conjunto exclusivo de funções. No entanto, o `{epiparameter}` oferece as mesmas quatro funções para acessar cada um dos valores acima para qualquer objeto `<epiparameter>` que você desejar! \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plote isto para ter uma referência visual\n\n# distribuição contínua\nplot(covid_serialint, xlim = c(0, 20))\n```\n\n::: {.cell-output-display}\n![](03-funcoes-de-atraso_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# o valor da densidade no valor de quantil 10 (dias)\ndensity(covid_serialint, at = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01911607\n```\n\n\n:::\n\n```{.r .cell-code}\n# a probabilidade acumulada no valor de quantil 10 (dias)\nepiparameter::cdf(covid_serialint, q = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9466605\n```\n\n\n:::\n\n```{.r .cell-code}\n# o valor do quantil (dia) a uma probabilidade acumulada de 60%\nquantile(covid_serialint, p = 0.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.618906\n```\n\n\n:::\n\n```{.r .cell-code}\n# gerar 10 valores aleatórios (dias) dada\n# a família de distribuição e seus parâmetros\nepiparameter::generate(covid_serialint, times = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 1.852761 2.823021 2.968270 2.781683 2.130811 2.613410 6.387306 2.986456\n [9] 4.248183 3.870598\n```\n\n\n:::\n:::\n\n\n::: {.callout-important title=\"Para o instrutor\" collapse=\"true\"}\n\nVocê pode acessar a documentação de referência (arquivos de ajuda) para essas funções com a notação de três dois-pontos: `epiparameter:::`\n\n- `?epiparameter:::density.epiparameter()`\n- `?epiparameter:::cdf.epiparameter()`\n- `?epiparameter:::quantile.epiparameter()`\n- `?epiparameter:::generate.epiparameter()`\n\n:::\n\n::: {.callout-tip .desafio title=\"Desafio\"}\n\n### Janela para rastreamento de contatos e o intervalo serial\n\nO **intervalo serial** é importante na otimização do rastreamento de contatos, pois fornece uma janela de tempo para a contenção da disseminação de uma doença ([Fine, 2003](https://academic.oup.com/aje/article/158/11/1039/162725)). Dependendo do intervalo serial, podemos avaliar a necessidade de aumentar o número de dias considerados para o rastreamento de contatos a fim de incluir mais contatos retrospectivos ([Davis et al., 2020](https://assets.publishing.service.gov.uk/media/61e9ab3f8fa8f50597fb3078/S0523_Oxford_-_Backwards_contact_tracing.pdf)).\n\nCom o intervalo serial da COVID-19 (`covid_serialint`), calcule:\n\n- Quanto a expansão da janela de rastreamento de contatos de 2 para 6 dias antes do início dos sintomas melhoraria a detecção de potenciais infectores?\n\n::: {.callout-note title=\"Dica\" collapse=\"true\"}\n\nO intervalo serial é o tempo entre o início dos sintomas em um infector e o início dos sintomas no indivíduo por ele infectado.\n\nPodemos usar a **distribuição do intervalo serial** para quantificar a probabilidade de detectar um infector a partir de um novo caso. \nEssa probabilidade pode ser calculada diretamente a partir da distribuição assumida. \nConsulte a Figura 2 em [Davis et al., 2020](https://assets.publishing.service.gov.uk/media/61e9ab3f8fa8f50597fb3078/S0523_Oxford_-_Backwards_contact_tracing.pdf).\n\nPara um objeto da classe `<epiparameter>`, a probabilidade acumulada pode ser calculada usando `epiparameter::cdf()`.\n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(covid_serialint)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calcular a probabilidade de encontrar casos retrospectivos\n# com janela de rastreamento de contatos de 2 dias\nwindow_2 <- epiparameter::cdf(covid_serialint, q = 2)\n\nwindow_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1111729\n```\n\n\n:::\n\n```{.r .cell-code}\n# calcular a probabilidade de encontrar casos retrospectivos\n# com janela de rastreamento de contatos de 6 dias\nwindow_6 <- epiparameter::cdf(covid_serialint, q = 6)\n\nwindow_6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7623645\n```\n\n\n:::\n\n```{.r .cell-code}\n# calcular a diferença\nwindow_6 - window_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6511917\n```\n\n\n:::\n:::\n\n\nDado o intervalo serial da COVID-19:\n\n- Um método de rastreamento de contatos que considere contatos até 2 dias antes do início dos sintomas capturará cerca de 11.1% dos casos retrospectivos.\n\n- Se esse período for estendido para 6 dias antes do início dos sintomas, isso poderá incluir 76.2% dos contatos retrospectivos.\n\n- Cerca de 65.1% a mais de casos retrospectivos poderiam ser capturados ao estender o rastreamento de 2 para 6 dias.\n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\n### E se\n\nSe invertermos a pergunta entre dias e probabilidade acumulada para: \n\n- Ao considerar casos secundários, em até quantos dias após o início dos sintomas dos casos primários podemos esperar que ocorra 55% do início dos sintomas secundários?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(covid_serialint, p = 0.55)\n```\n:::\n\n\nUma interpretação poderia ser:\n\n- 55% dos casos secundários terão o início de seus sintomas em cerca de 4,3 dias a partir do início dos sintomas no caso primário.\n\n:::\n\n:::\n\n## Discretizar uma distribuição contínua\n\nEstamos chegando mais perto do final! O `EpiNow2::LogNormal()` ainda precisa de um valor máximo (`max`). \n\nUma forma de fazer isso é obter o valor do quantil para o 99º percentil da distribuição ou probabilidade acumulada de `0.99`. Para isso, precisamos acessar o conjunto de funções de distribuição para o nosso objeto `<epiparameter>`.\n\nPodemos usar o conjunto de funções de distribuição para uma distribuição _contínua_ (como acima). No entanto, esses valores serão números _contínuos_. Podemos **discretizar** a distribuição contínua armazenada em nosso objeto `<epiparameter>` para obter valores discretos a partir de uma distribuição contínua.\n\nQuando usamos `epiparameter::discretise()` na distribuição contínua, obtemos uma distribuição **discreta**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_serialint_discrete <-\n  epiparameter::discretise(covid_serialint)\n\ncovid_serialint_discrete\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDisease: COVID-19\nPathogen: SARS-CoV-2\nEpi Parameter: serial interval\nStudy: Nishiura H, Linton N, Akhmetzhanov A (2020). \"Serial interval of novel\ncoronavirus (COVID-19) infections.\" _International Journal of\nInfectious Diseases_. doi:10.1016/j.ijid.2020.02.060\n<https://doi.org/10.1016/j.ijid.2020.02.060>.\nDistribution: discrete lnorm (days)\nParameters:\n  meanlog: 1.386\n  sdlog: 0.568\n```\n\n\n:::\n:::\n\n\nIdentificamos essa mudança na linha de saída `Distribution:` do objeto `<epiparameter>`. Confira esta linha:\n\n```\nDistribution: discrete lnorm (days)\n```\n\nEnquanto para uma distribuição **contínua** plotamos a *Função Densidade de Probabilidade (PDF)*, para uma distribuição **discreta** plotamos a *Função Massa de Probabilidade (PMF)*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# distribuição discreta\nplot(covid_serialint_discrete)\n```\n\n::: {.cell-output-display}\n![](03-funcoes-de-atraso_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nPara finalmente obter um valor `max`, vamos acessar o valor do quantil do 99º percentil ou probabilidade acumulada de `0.99` da distribuição usando a função `quantile()`, como fizemos acima para a distribuição contínua.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_serialint_discrete_max <-\n  quantile(covid_serialint_discrete, p = 0.99)\n```\n:::\n\n\n::: {.callout-tip .desafio title=\"Desafio\"}\n\n### Duração da quarentena e período de incubação\n\nA distribuição do **período de incubação** é um atraso útil para avaliar a duração do monitoramento ativo ou da quarentena ([Lauer et al., 2020](https://www.acpjournals.org/doi/10.7326/M20-0504)). Da mesma forma, atrasos do início dos sintomas até a recuperação (ou óbito) determinarão a duração necessária da assistência à saúde e do isolamento de casos ([Cori et al., 2017](https://royalsocietypublishing.org/doi/10.1098/rstb.2016.0371)).\n\nA biblioteca de parâmetros no pacote `{epiparameter}` contém os parâmetros relatados por [Lauer et al., 2020](https://www.acpjournals.org/doi/10.7326/M20-0504).\n\nCalcule:\n\n- Quantos dias após a infecção 99% das pessoas que desenvolverão sintomas de COVID-19 de fato manifestam sintomas? Obtenha um número inteiro como resposta.\n\n::: {.callout-note title=\"Dica\" collapse=\"true\"}\n\nQual distribuição de atraso mede o tempo entre a infecção e o início dos sintomas?\nPara relembrar, você pode ler o [Glossário](../glossario.qmd) do tutorial.\n\nAs funções de probabilidade para distribuições **discretas** do `<epiparameter>` são as mesmas que usamos para as *contínuas*!\n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# o atraso da infecção até o início dos sintomas é chamado de período de incubação\n# acessar o período de incubação para covid\ncovid_incubation <-\n  epiparameter::epiparameter_db(\n    disease = \"covid\",\n    epi_name = \"incubation\",\n    author = \"lauer\",\n    single_epiparameter = TRUE\n  )\n\ncovid_incubation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDisease: COVID-19\nPathogen: SARS-CoV-2\nEpi Parameter: incubation period\nStudy: Lauer S, Grantz K, Bi Q, Jones F, Zheng Q, Meredith H, Azman A, Reich\nN, Lessler J (2020). \"The Incubation Period of Coronavirus Disease 2019\n(COVID-19) From Publicly Reported Confirmed Cases: Estimation and\nApplication.\" _Annals of Internal Medicine_. doi:10.7326/M20-0504\n<https://doi.org/10.7326/M20-0504>.\nDistribution: lnorm (days)\nParameters:\n  meanlog: 1.629\n  sdlog: 0.419\n```\n\n\n:::\n\n```{.r .cell-code}\n# para obter um número inteiro como resposta, discretize a distribuição\ncovid_incubation_discrete <- epiparameter::discretise(covid_incubation)\n\ncovid_incubation_discrete\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDisease: COVID-19\nPathogen: SARS-CoV-2\nEpi Parameter: incubation period\nStudy: Lauer S, Grantz K, Bi Q, Jones F, Zheng Q, Meredith H, Azman A, Reich\nN, Lessler J (2020). \"The Incubation Period of Coronavirus Disease 2019\n(COVID-19) From Publicly Reported Confirmed Cases: Estimation and\nApplication.\" _Annals of Internal Medicine_. doi:10.7326/M20-0504\n<https://doi.org/10.7326/M20-0504>.\nDistribution: discrete lnorm (days)\nParameters:\n  meanlog: 1.629\n  sdlog: 0.419\n```\n\n\n:::\n\n```{.r .cell-code}\n# calcular o quantil ou valor no 99º percentil a partir da distribuição\nquantile(covid_incubation_discrete, p = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13\n```\n\n\n:::\n:::\n\n\n99% daqueles que desenvolvem sintomas de COVID-19 o farão em até 13 dias após a infecção.\n\nAgora, esse resultado é consistente com a duração da quarentena recomendada na prática durante a pandemia de COVID-19?\n\n:::\n\n:::\n\n::: {.callout-important title=\"Para o instrutor\" collapse=\"true\"}\n\n**Como criar um gráfico de distribuição?**\n\nA partir de um valor máximo com `quantile()`, podemos criar uma sequência de valores de quantis como um vetor numérico e calcular os valores de `density()` para cada um:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# criar uma visualização da distribuição discreta\n# a partir de um valor máximo da distribuição\nquantile(covid_serialint_discrete, p = 0.99) %>%\n  # gerar valores de quantis\n  # como uma sequência para cada número natural\n  seq(1L, to = ., by = 1L) %>%\n  # converter vetor numérico em data frame\n  as_tibble_col(column_name = \"quantile_values\") %>%\n  mutate(\n    # calcular valores de densidade\n    # para cada quantil na função densidade\n    density_values =\n      density(\n        x = covid_serialint_discrete,\n        at = quantile_values\n      )\n  ) %>%\n  # criar o gráfico\n  ggplot(\n    aes(\n      x = quantile_values,\n      y = density_values\n    )\n  ) +\n  geom_col()\n```\n\n::: {.cell-output-display}\n![](03-funcoes-de-atraso_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n**Lembre-se:** Em infecções com transmissão pré-sintomática, os intervalos seriais podem ter valores negativos ([Nishiura et al., 2020](https://www.ijidonline.com/article/S1201-9712(20)30119-3/fulltext)). Quando usamos o _intervalo serial_ para aproximar o _tempo de geração_, precisamos fazer com que essa distribuição tenha apenas valores positivos!\n\n:::\n\n## Conectar o `{epiparameter}` ao `{EpiNow2}`\n\nAgora podemos inserir tudo na função `EpiNow2::LogNormal()`!\n\n- as **estatísticas resumo** `mean` e `sd` da distribuição,\n- um valor máximo `max`,\n- o nome da `distribution`.\n\nAo usar `EpiNow2::LogNormal()` para definir uma distribuição **log-normal** como aquela no objeto `covid_serialint`, podemos especificar a média e o desvio padrão como parâmetros. Como alternativa, para obter os parâmetros \"naturais\" de uma distribuição log-normal, podemos converter suas estatísticas resumo em parâmetros da distribuição chamados `meanlog` e `sdlog`. Com o `{epiparameter}`, podemos obter diretamente os *parâmetros da distribuição* usando `epiparameter::get_parameters()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_serialint_parameters <-\n  epiparameter::get_parameters(covid_serialint)\n```\n:::\n\n\nEntão, temos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nserial_interval_covid <-\n  EpiNow2::LogNormal(\n    meanlog = covid_serialint_parameters[\"meanlog\"],\n    sdlog = covid_serialint_parameters[\"sdlog\"],\n    max = covid_serialint_discrete_max\n  )\n\nserial_interval_covid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- lognormal distribution (max: 14):\n  meanlog:\n    1.4\n  sdlog:\n    0.57\n```\n\n\n:::\n:::\n\n\n::: {.callout-important title=\"Para o instrutor\" collapse=\"true\"}\n\nPodemos interromper a codificação ao vivo (livecoding) nesta etapa e prosseguir com a parte prática.\n\n:::\n\n::: {.callout-tip .desafio title=\"Desafio\"}\n\n## LogNormal ou Gamma?\n\nDigamos que você precise quantificar a transmissão de um surto de Ebola. \nVocê usará o intervalo serial como uma aproximação do tempo de geração para o `{EpiNow2}`.\nO `{epiparameter}` lhe dará acesso ao parâmetro estimado a partir de surtos históricos.\n\nSiga estas etapas:\n\n- Obtenha acesso à distribuição do `serial interval` de `Ebola` usando o `{epiparameter}`.\n- Acesse uma entrada do estudo com o maior tamanho amostral.- Imprima a saída e leia a descrição.\n- Identifique qual distribuição de probabilidade (por exemplo, Gamma, LogNormal, etc.) foi usada pelos autores para modelar o atraso.\n- Extraia os parâmetros da distribuição para a distribuição de probabilidade correspondente.\n- Calcule um valor máximo exato para a distribuição de atraso (por exemplo, o 99º percentil).\n- Insira os parâmetros da distribuição do `<epiparameter>` na função de distribuição de probabilidade correspondente no `{EpiNow2}`\n(por exemplo, `EpiNow2::Gamma()`, `EpiNow2::LogNormal()`, etc.).\n\n::: {.callout-note title=\"Dica\" collapse=\"true\"}\n\nAo conectar `{epiparameter}` e `{EpiNow2}`, há uma etapa que é suscetível a erros. \n\nNo `<epiparameter>`, a linha de saída `Distribution:` determina a função a ser usada no `{EpiNow2}`:\n\nEscolhemos `EpiNow2::Gamma()` se no `<epiparameter>` obtivermos:\n\n```\nDistribution: gamma (days)\nParameters:\n  shape: 2.188\n  scale: 6.490\n```\n\nEscolhemos `EpiNow2::LogNormal()` se no `<epiparameter>` obtivermos:\n\n```\nDistribution: lnorm (days)\nParameters:\n  meanlog: 1.386\n  sdlog: 0.568\n```\n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. acessar um intervalo serial\nebola_serialint <- epiparameter::epiparameter_db(\n  disease = \"ebola\",\n  epi_name = \"serial\",\n  single_epiparameter = TRUE\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nebola_serialint\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDisease: Ebola Virus Disease\nPathogen: Ebola Virus\nEpi Parameter: serial interval\nStudy: WHO Ebola Response Team, Agua-Agum J, Ariyarajah A, Aylward B, Blake I,\nBrennan R, Cori A, Donnelly C, Dorigatti I, Dye C, Eckmanns T, Ferguson\nN, Formenty P, Fraser C, Garcia E, Garske T, Hinsley W, Holmes D,\nHugonnet S, Iyengar S, Jombart T, Krishnan R, Meijers S, Mills H,\nMohamed Y, Nedjati-Gilani G, Newton E, Nouvellet P, Pelletier L,\nPerkins D, Riley S, Sagrado M, Schnitzler J, Schumacher D, Shah A, Van\nKerkhove M, Varsaneux O, Kannangarage N (2015). \"West African Ebola\nEpidemic after One Year — Slowing but Not Yet under Control.\" _The New\nEngland Journal of Medicine_. doi:10.1056/NEJMc1414992\n<https://doi.org/10.1056/NEJMc1414992>.\nDistribution: gamma (days)\nParameters:\n  shape: 2.188\n  scale: 6.490\n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. extrair parâmetros do objeto {epiparameter}\nebola_serialint_params <- epiparameter::get_parameters(ebola_serialint)\n\nebola_serialint_params\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   shape    scale \n2.187934 6.490141 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. obter um valor máximo\nebola_serialint_max <- ebola_serialint %>%\n  epiparameter::discretise() %>%\n  quantile(p = 0.99)\n\nebola_serialint_max\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 45\n```\n\n\n:::\n\n```{.r .cell-code}\n# 4. adaptar o {epiparameter} para a interface de distribuição do {EpiNow2}\nebola_generationtime <- EpiNow2::Gamma(\n  shape = ebola_serialint_params[\"shape\"],\n  scale = ebola_serialint_params[\"scale\"],\n  max = ebola_serialint_max\n)\n\nebola_generationtime\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- gamma distribution (max: 45):\n  shape:\n    2.2\n  rate:\n    0.15\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plotar o objeto da classe `epiparameter`\nplot(ebola_serialint)\n```\n\n::: {.cell-output-display}\n![](03-funcoes-de-atraso_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plotar o objeto da classe `dist_spec` do {EpiNow2}\nplot(ebola_generationtime)\n```\n\n::: {.cell-output-display}\n![](03-funcoes-de-atraso_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nPlotar distribuições a partir da interface do `{EpiNow2}` sempre produz uma saída discretizada.\nA partir da legenda: `PMF` significa Função Massa de Probabilidade (*Probability Mass Function*) e `CMF` significa Função Massa Acumulada (*Cumulative Mass Function*).\n\n:::\n\n:::\n\n## Ajustar para atrasos de notificação\n\nEstimar o $R_t$ requer dados sobre o número diário de novas infecções. Devido a defasagens no desenvolvimento de cargas virais detectáveis, início dos sintomas, busca por atendimento e notificação, esses números não estão prontamente disponíveis. Todas as observações refletem eventos de transmissão ocorridos em algum momento no passado. Em outras palavras, se $d$ é o atraso da infecção até a observação, então observações no tempo $t$ orientam $R_{t−d}$, e não $R_t$. [(Gostic et al., 2020)](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008409#sec007)\n\n![**Linha do tempo para a cadeia de notificação de doenças, Países Baixos.** Lab, laboratório; PHA, autoridade de saúde pública (*public health authority*). De [Marinović et al., 2015](https://wwwnc.cdc.gov/eid/article/21/2/13-0504_article)](../img/disease-reporting.jpg)\n\nA **distribuição de atraso** pode ser inferida conjuntamente com os momentos subjacentes de infecção ou estimada como a soma da distribuição do [período de incubação](../glossario.qmd#incubation) e da distribuição dos atrasos do início dos sintomas até a observação a partir de dados de linelist ([atraso de notificação](../glossario.qmd#reportingdelay)). Para o `{EpiNow2}`, podemos especificar essas duas distribuições de atraso complementares no argumento `delays`.\n\n::: {.callout-note title=\"No Brasil: medir o atraso de notificação\"}\n\nNas bases do SINAN e do SIVEP-Gripe, o atraso de notificação pode ser medido diretamente pela\ndiferença entre a data de primeiros sintomas e a data de notificação ou de digitação. Como as\núltimas semanas ainda não foram consolidadas, esse atraso aparece como censura à direita — e é\nexatamente o que este episódio ensina a representar como distribuição. Fonte: [SINAN — instrucional para download de microdados](http://portalsinan.saude.gov.br/images/documentos/Agravos/microdados/INSTRUCIONAL_PARA_DOWNLOAD_DE_MICRODADOS_DO_SINAN.pdf).\n\n:::\n\n![**$R_{t}$ é uma medida de transmissão no tempo $t$.** Observações após o tempo $t$ devem ser ajustadas. UTI, unidade de terapia intensiva (*ICU*). De [Gostic et al., 2020](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008409#sec007)](../img/rt-adjusting-delays.png)\n\n::: {.callout-tip .desafio title=\"Desafio\"}\n\n### Usar um período de incubação para COVID-19 para estimar o Rt\n\nEstime o número de reprodução variável no tempo para os primeiros 60 dias do conjunto de dados `example_confirmed` do `{EpiNow2}`. Acesse um período de incubação para COVID-19 do `{epiparameter}` para usá-lo como um atraso de notificação.\n\n::: {.callout-note title=\"Dica\" collapse=\"true\"}\n\nUse o último cálculo de `epinow()` utilizando o argumento `delays` e a função auxiliar `delay_opts()`.\n\nO argumento `delays` e a função auxiliar `delay_opts()` são análogos ao argumento `generation_time` e à função auxiliar `generation_time_opts()`.\n\n```r\nepinow_estimates <- EpiNow2::epinow(\n  # casos\n  data = example_confirmed[1:60],\n  # atrasos\n  generation_time = EpiNow2::generation_time_opts(covid_serial_interval),\n  delays = EpiNow2::delay_opts(covid_incubation_time)\n)\n```\n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tempo de geração --------------------------------------------------------\n\n# obter o intervalo serial da covid\ncovid_serialint <-\n  epiparameter::epiparameter_db(\n    disease = \"covid\",\n    epi_name = \"serial\",\n    single_epiparameter = TRUE\n  )\n\n# adaptar epiparameter para epinow2\ncovid_serialint_discrete_max <- covid_serialint %>%\n  epiparameter::discretise() %>%\n  quantile(p = 0.99)\n\ncovid_serialint_parameters <-\n  epiparameter::get_parameters(covid_serialint)\n\ncovid_serial_interval <-\n  EpiNow2::LogNormal(\n    meanlog = covid_serialint_parameters[\"meanlog\"],\n    sdlog = covid_serialint_parameters[\"sdlog\"],\n    max = covid_serialint_discrete_max\n  )\n\n# tempo de incubação ------------------------------------------------------\n\n# obter o período de incubação da covid\ncovid_incubation <- epiparameter::epiparameter_db(\n  disease = \"covid\",\n  epi_name = \"incubation\",\n  single_epiparameter = TRUE\n)\n\n# adaptar epiparameter para epinow2\ncovid_incubation_discrete_max <- covid_incubation %>%\n  epiparameter::discretise() %>%\n  quantile(p = 0.99)\n\ncovid_incubation_parameters <-\n  epiparameter::get_parameters(covid_incubation)\n\ncovid_incubation_time <-\n  EpiNow2::LogNormal(\n    meanlog = covid_incubation_parameters[\"meanlog\"],\n    sdlog = covid_incubation_parameters[\"sdlog\"],\n    max = covid_incubation_discrete_max\n  )\n\n# epinow ------------------------------------------------------------------\n\n# Definir 4 núcleos para serem usados em computações paralelas\nwithr::local_options(list(mc.cores = parallel::detectCores() - 1))\n\n# executar epinow\nepinow_estimates_cgi <- EpiNow2::epinow(\n  # casos\n  data = example_confirmed[1:60],\n  # atrasos\n  generation_time = EpiNow2::generation_time_opts(covid_serial_interval),\n  delays = EpiNow2::delay_opts(covid_incubation_time)\n)\n\nbase::plot(epinow_estimates_cgi)\n```\n\n::: {.cell-output-display}\n![](03-funcoes-de-atraso_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nTente complementar o argumento `delays` com um atraso de notificação como o objeto `reporting_delay_fixed` do episódio anterior.\n\n:::\n\n:::\n\n::: {.callout-note title=\"Discussão\"}\n\n### O quanto mudou?\n\nCompare três execuções de `EpiNow2::epinow()`:\n\n- Usar apenas o tempo de geração\n- Adicionar o tempo de incubação\n- Adicionar o tempo de incubação e o atraso de notificação\n\nApós adicionar todos os atrasos, discuta:\n\n- A tendência do ajuste do modelo na seção \"Estimate\" muda?\n- A incerteza mudou?\n- Como você explicaria ou interpretaria qualquer uma dessas mudanças?\n\nCompare todas as figuras do `{EpiNow2}` geradas nas três execuções.\n\n:::\n\n## Desafios\n\n::: {.callout-note}\n\n### Uma dica de autocompletar código\n\nSe escrevermos `[]` ao lado do objeto `covid_serialint_parameters[]`, dentro de `[]` podemos usar a \ntecla Tab <kbd>↹</kbd> \npara o [recurso de autocompletar código](https://support.posit.co/hc/en-us/articles/205273297-Code-Completion-in-the-RStudio-IDE) \n\nIsso dá acesso rápido a `covid_serialint_parameters[\"meanlog\"]` e `covid_serialint_parameters[\"sdlog\"]`. \n\nConvidamos você a experimentar isso nos blocos de código e no console do R!\n\n:::\n\n::: {.callout-tip .desafio title=\"Desafio\"}\n\n### Número de reprodução efetivo do Ebola ajustado por atrasos de notificação \n\nBaixe e leia o [conjunto de dados de Ebola](../data/ebola_cases.csv):\n\n- Estime o número de reprodução efetivo usando o `{EpiNow2}` \n- Ajuste a estimativa pelos atrasos de notificação disponíveis no `{epiparameter}`\n- Por que você escolheu esse parâmetro?\n\n::: {.callout-note title=\"Dica\" collapse=\"true\"}\n\nPara calcular o $R_t$ usando o `{EpiNow2}`, precisamos de:\n\n- `data` de incidência agregada, com casos confirmados por dia, e\n- A distribuição do tempo de geração (`generation`).\n- Opcionalmente, distribuições de atrasos de notificação (`delays`) quando disponíveis (por exemplo, período de incubação).\n\nPara obter distribuições de atraso usando o `{epiparameter}`, podemos usar funções como:\n\n- `epiparameter::epiparameter_db()`\n- `epiparameter::parameter_tbl()`\n- `discretise()`\n- `quantile()` \n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ler dados\n# ex.: se o caminho para o arquivo for data/raw-data/ebola_cases.csv então:\nebola_confirmed <-\n  read_csv(here::here(\"data\", \"raw-data\", \"ebola_cases.csv\")) %>%\n  incidence2::incidence(\n    date_index = \"date\",\n    counts = \"confirm\",\n    count_values_to = \"confirm\",\n    date_names_to = \"date\",\n    complete_dates = TRUE\n  ) %>%\n  dplyr::select(-count_variable)\n\n# listar distribuições\nepiparameter::epiparameter_db(disease = \"ebola\") %>%\n  epiparameter::parameter_tbl()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tempo de geração --------------------------------------------------------\n\n# selecionar uma distribuição para o tempo de geração\nebola_serial <- epiparameter::epiparameter_db(\n  disease = \"ebola\",\n  epi_name = \"serial\",\n  single_epiparameter = TRUE\n)\n\n# adaptar epiparameter para epinow2\nebola_serial_discrete <- epiparameter::discretise(ebola_serial)\n\nserial_interval_ebola <-\n  EpiNow2::Gamma(\n    mean = ebola_serial$summary_stats$mean,\n    sd = ebola_serial$summary_stats$sd,\n    max = quantile(ebola_serial_discrete, p = 0.99)\n  )\n\n# tempo de incubação ------------------------------------------------------\n\n# selecionar uma distribuição para o atraso do período de incubação\nebola_incubation <- epiparameter::epiparameter_db(\n  disease = \"ebola\",\n  epi_name = \"incubation\",\n  single_epiparameter = TRUE\n)\n\n# adaptar epiparameter para epinow2\nebola_incubation_discrete <- epiparameter::discretise(ebola_incubation)\n\nincubation_period_ebola <-\n  EpiNow2::Gamma(\n    mean = ebola_incubation$summary_stats$mean,\n    sd = ebola_incubation$summary_stats$sd,\n    max = quantile(ebola_incubation_discrete, p = 0.99)\n  )\n\n# epinow ------------------------------------------------------------------\n\n# executar epinow\nepinow_estimates_egi <- EpiNow2::epinow(\n  # casos\n  data = ebola_confirmed,\n  # atrasos\n  generation_time = EpiNow2::generation_time_opts(serial_interval_ebola),\n  delays = EpiNow2::delay_opts(incubation_period_ebola)\n)\n\nplot(epinow_estimates_egi)\n```\n\n::: {.cell-output-display}\n![](03-funcoes-de-atraso_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n:::\n\n:::\n\n::: {.callout-tip .desafio title=\"Desafio\"}\n\n### O que fazer com distribuições Weibull?\n\nUse o conjunto de dados `influenza_england_1978_school` do pacote `{outbreaks}` para calcular o número de reprodução efetivo usando o `{EpiNow2}`, ajustando pelos atrasos de notificação disponíveis no `{epiparameter}`.\n\n::: {.callout-note title=\"Dica\" collapse=\"true\"}\n\n`EpiNow2::NonParametric()` aceita Funções Massa de Probabilidade (PMF) de qualquer família de distribuição. Leia o guia de referência sobre [Distribuições de probabilidade](https://epiforecasts.io/EpiNow2/reference/Distributions.html).\n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quais parâmetros estão disponíveis para Influenza?\nepiparameter::epiparameter_db(disease = \"influenza\") %>%\n  epiparameter::parameter_tbl() %>%\n  count(epi_name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Parameter table:\n# A data frame:    3 × 2\n  epi_name              n\n  <chr>             <int>\n1 generation time       1\n2 incubation period    15\n3 serial interval       1\n```\n\n\n:::\n\n```{.r .cell-code}\n# tempo de geração --------------------------------------------------------\n\n# Ler o tempo de geração\ninfluenza_generation <-\n  epiparameter::epiparameter_db(\n    disease = \"influenza\",\n    epi_name = \"generation\"\n  )\n\ninfluenza_generation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDisease: Influenza\nPathogen: Influenza-A-H1N1\nEpi Parameter: generation time\nStudy: Lessler J, Reich N, Cummings D, New York City Department of Health and\nMental Hygiene Swine Influenza Investigation Team (2009). \"Outbreak of\n2009 Pandemic Influenza A (H1N1) at a New York City School.\" _The New\nEngland Journal of Medicine_. doi:10.1056/NEJMoa0906089\n<https://doi.org/10.1056/NEJMoa0906089>.\nDistribution: weibull (days)\nParameters:\n  shape: 2.360\n  scale: 3.180\n```\n\n\n:::\n\n```{.r .cell-code}\n# O EpiNow2 aceita atualmente Gamma ou LogNormal\n# outros podem passar a função PMF\n\ninfluenza_generation_discrete <-\n  epiparameter::discretise(influenza_generation)\n\ninfluenza_generation_max <-\n  quantile(influenza_generation_discrete, p = 0.99)\n\ninfluenza_generation_pmf <-\n  density(\n    influenza_generation_discrete,\n    at = 0:influenza_generation_max\n  )\n\ninfluenza_generation_pmf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.00000000 0.06312336 0.22134988 0.29721220 0.23896828 0.12485164 0.04309454\n```\n\n\n:::\n\n```{.r .cell-code}\n# EpiNow2::NonParametric() também pode aceitar os valores da PMF\ngeneration_time_influenza <-\n  EpiNow2::NonParametric(\n    pmf = influenza_generation_pmf\n  )\n\n# período de incubação ----------------------------------------------------\n\n# Ler o período de incubação\ninfluenza_incubation <-\n  epiparameter::epiparameter_db(\n    disease = \"influenza\",\n    epi_name = \"incubation\",\n    single_epiparameter = TRUE\n  )\n\n# Discretizar o período de incubação\ninfluenza_incubation_discrete <-\n  epiparameter::discretise(influenza_incubation)\n\ninfluenza_incubation_max <-\n  quantile(influenza_incubation_discrete, p = 0.99)\n\ninfluenza_incubation_pmf <-\n  density(\n    influenza_incubation_discrete,\n    at = 0:influenza_incubation_max\n  )\n\ninfluenza_incubation_pmf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.00000000 0.05749151 0.16687705 0.22443092 0.21507632 0.16104546 0.09746609\n[8] 0.04841928\n```\n\n\n:::\n\n```{.r .cell-code}\n# EpiNow2::NonParametric() também pode aceitar os valores da PMF\nincubation_time_influenza <-\n  EpiNow2::NonParametric(\n    pmf = influenza_incubation_pmf\n  )\n\n# epinow ------------------------------------------------------------------\n\n# Ler os dados\ninfluenza_cleaned <-\n  outbreaks::influenza_england_1978_school %>%\n  select(date, confirm = in_bed)\n\n# Executar epinow()\nepinow_estimates_igi <- EpiNow2::epinow(\n  # casos\n  data = influenza_cleaned,\n  # atrasos\n  generation_time = EpiNow2::generation_time_opts(generation_time_influenza),\n  delays = EpiNow2::delay_opts(incubation_time_influenza)\n)\n\nplot(epinow_estimates_igi)\n```\n\n::: {.cell-output-display}\n![](03-funcoes-de-atraso_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n:::\n\n:::\n\n## Próximos passos\n\n::: {.callout-note title=\"Para se aprofundar\"}\n\n### Como obter parâmetros da distribuição a partir de distribuições estatísticas?\n\nComo obter a média e o desvio padrão a partir de um tempo de geração com *apenas* parâmetros da distribuição, mas sem estatísticas resumo como `mean` ou `sd` para `EpiNow2::Gamma()` ou `EpiNow2::LogNormal()`?\n\nConsulte a vinheta do `{epiparameter}` sobre [extração e conversão de parâmetros](https://epiverse-trace.github.io/epiparameter/articles/extract_convert.html) e seus [casos de uso](https://epiverse-trace.github.io/epiparameter/articles/extract_convert.html#use-cases)!\n\n:::\n\n::: {.callout-note title=\"Para se aprofundar\"}\n\n### Como estimar distribuições de atraso para a Doença X?\n\nConsulte este excelente tutorial sobre a estimativa do intervalo serial e do período de incubação da Doença X levando em conta a *censura* por meio de inferência bayesiana com pacotes como `{rstan}` e `{coarseDataTools}`.\n\n- Tutorial em inglês: <https://rpubs.com/tracelac/diseaseX>- Tutorial em espanhol: <https://epiverse-trace.github.io/epimodelac/EnfermedadX.html>\n\n**Depois,** após obter seus valores estimados, você pode criar manualmente seus próprios objetos da classe `<epiparameter>` com `epiparameter::epiparameter()`! Dê uma olhada no seu [guia de referência sobre \"Criar um objeto `<epiparameter>`\"](https://epiverse-trace.github.io/epiparameter/reference/epiparameter.html#ref-examples)!\n\nPor fim, confira os pacotes R mais recentes [{epidist}](https://epidist.epinowcast.org/) e [{primarycensored}](https://primarycensored.epinowcast.org/), que fornecem métodos para lidar com os principais desafios na estimativa de distribuições, incluindo truncamento, censura intervalar e vieses dinâmicos.\n\n:::\n\n<!--\n## Mapa conceitual\n\natualizar a partir do último teste do epiparameter\n-->\n\n::: {.callout-note title=\"Pontos-chave\"}\n\n- Use funções de distribuição com objetos `<epiparameter>` para obter estatísticas resumo e parâmetros informativos para intervenções de saúde pública, como a Janela para rastreamento de contatos e a Duração da quarentena.\n- Use `discretise()` para converter distribuições de atraso contínuas em discretas.\n- Use o `{epiparameter}` para obter atrasos de notificação necessários nas estimativas de transmissibilidade.\n\n:::\n",
    "supporting": [
      "03-funcoes-de-atraso_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}