{
  "hash": "77e378dcece6c0fdccffc60eb3f42fc6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Quantificar a transmissibilidade'\n---\n\n::: {.callout-note title=\"Perguntas\"}\n\n- Como posso estimar o número de reprodução variante no tempo ($R_t$) e a taxa de crescimento a partir de uma série temporal de dados de casos?\n- Como posso quantificar a heterogeneidade geográfica a partir dessas métricas de transmissão?\n\n:::\n\n::: {.callout-tip title=\"Objetivos\"}\n\n- Aprender a estimar métricas de transmissão a partir de uma série temporal de dados de casos usando o pacote R `{EpiNow2}`\n\n:::\n\n::: {.callout-important title=\"Pré-requisitos\"}\n\n## Pré-requisitos\n\nVocê deve se familiarizar com os seguintes conceitos antes de trabalhar neste tutorial:\n\n**Estatística**: [distribuições de probabilidade](https://epiverse-trace.github.io/tutorials/), princípios de análise bayesiana.\n\n**Teoria epidêmica**: [Tempo de geração](01-acessar-atrasos.qmd), número de reprodução efetivo.\n\n**Ciência de dados**: transformação e visualização de dados. Você pode revisar o episódio sobre [agregar e visualizar](https://epiverse-trace.github.io/tutorials-early/aggreagate-visualize.html) dados de incidência.\n\n**Pacotes R instalados**: `{EpiNow2}`, `{incidence2}`, `{tidyverse}`.\n\n:::\n\n::: {.callout-note title=\"Detalhes\" collapse=\"true\"}\n\nInstale os pacotes se eles ainda não estiverem instalados (se desejar, você pode configurar o espelho brasileiro do CRAN com `options(repos = c(CRAN = \"https://cran-r.c3sl.ufpr.br/\"))`):\n\n```r\nif (!base::require(\"pak\")) install.packages(\"pak\")\npak::pak(c(\"EpiNow2\", \"incidence2\", \"tidyverse\"))\n```\n\nSe você receber alguma mensagem de erro,\nacesse a [página principal de configuração](../setup.qmd#software-setup).\n\n:::\n\n::: {.callout-note}\n\n### Lembrete: o número de reprodução efetivo, $R_t$\n\nO [número de reprodução básico](../glossario.qmd#basic), $R_0$, é o número médio de casos causados por um indivíduo infeccioso em uma população totalmente suscetível.\n\nMas em um surto em andamento, a população não permanece totalmente suscetível, pois aqueles que se recuperam da infecção geralmente adquirem imunidade. Além disso, podem ocorrer mudanças no comportamento ou outros fatores que afetam a transmissão.\n\nQuando temos interesse em monitorar as mudanças na transmissão, estamos mais interessados no valor do **número de reprodução efetivo**, $R_t$, que representa o número médio de casos causados por um indivíduo infeccioso na população no tempo $t$, dado o estado atual da população (incluindo níveis de imunidade e medidas de controle).\n\n:::\n\n## Introdução\n\nA intensidade de transmissão de um surto é quantificada usando duas métricas fundamentais: o número de reprodução, que informa sobre a força da transmissão ao indicar quantos novos casos são esperados a partir de cada caso existente; e a [taxa de crescimento](../glossario.qmd#growth), que informa sobre a velocidade da transmissão ao indicar a rapidez com que o surto está se propagando ou diminuindo (tempo de duplicação/tempo de redução pela metade) em uma população. Para mais detalhes sobre a distinção entre velocidade e força de transmissão e suas implicações para o controle, consulte [Dushoff & Park, 2021](https://royalsocietypublishing.org/doi/full/10.1098/rspb.2020.1556).\n\nPara estimar essas métricas fundamentais usando dados de casos, precisamos levar em conta os atrasos entre a data das infecções e a data dos casos notificados. Em uma situação de surto, os dados geralmente estão disponíveis apenas por datas de notificação; portanto, devemos usar métodos de estimação para corrigir para esses atrasos ao tentar entender as mudanças na transmissão ao longo do tempo.\n\nNos próximos tutoriais, nosso foco será em como usar as funções do `{EpiNow2}` para estimar métricas de transmissão a partir de dados de casos. Não abordaremos a fundamentação teórica dos modelos ou da estrutura de inferência; para detalhes sobre esses conceitos, consulte a [vinheta](https://epiforecasts.io/EpiNow2/dev/articles/estimate_infections.html).\n\nNeste tutorial, aprenderemos a usar o pacote `{EpiNow2}` para estimar o número de reprodução variante no tempo. Obteremos os dados de entrada do `{incidence2}`. Usaremos os pacotes `{tidyr}` e `{dplyr}` para organizar algumas de suas saídas, o `{ggplot2}` para visualizar a distribuição dos casos e o operador pipe `%>%` para encadear algumas de suas funções; portanto, vamos carregar também o pacote `{tidyverse}`:\n\n```r\nlibrary(EpiNow2)\nlibrary(incidence2)\nlibrary(tidyverse)\n```\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note title=\"Checklist\"}\n\n### Os dois-pontos duplos\n\nOs dois-pontos duplos `::` no R permitem chamar uma função específica de um pacote sem carregar o pacote inteiro no ambiente atual.\n\nPor exemplo, `dplyr::filter(data, condition)` usa `filter()` do pacote `{dplyr}`.\n\nIsso nos ajuda a lembrar as funções dos pacotes e a evitar conflitos de namespace.\n\n:::\n\n::: {.callout-important title=\"Para o instrutor\" collapse=\"true\"}\n\nEste tutorial ilustra o uso de `epinow()` para estimar o número de reprodução variante no tempo e os momentos de infecção. As pessoas participantes devem compreender as entradas necessárias para o modelo e as limitações das saídas geradas.\n\n:::\n\n::: {.callout-note}\n\n### Inferência bayesiana\n\nO pacote R `EpiNow2` usa uma estrutura de [inferência bayesiana](../glossario.qmd#bayesian) para estimar números de reprodução e momentos de infecção com base nas datas de notificação. Em outras palavras, ele estima a transmissão com base em quando as pessoas foram efetivamente infectadas (em vez do início dos sintomas), levando em conta os atrasos nos dados observados. Em contrapartida, o pacote `{EpiEstim}` permite uma estimação em tempo real mais rápida e simples do número de reprodução usando apenas dados de casos ao longo do tempo, refletindo como a transmissão varia com base em quando os sintomas aparecem.\n\nNa inferência bayesiana, usamos o conhecimento a priori (distribuições a priori) com os dados (em uma função de verossimilhança) para encontrar a probabilidade a posteriori:\n\n$Posterior \\, probability \\propto likelihood \\times prior \\, probability$\n\n:::\n\n::: {.callout-important title=\"Para o instrutor\" collapse=\"true\"}\n\nFaça referência à distribuição de probabilidade a priori e à distribuição de [probabilidade a posteriori](https://en.wikipedia.org/wiki/Posterior_probability).\n\nNo [callout \"`Expected change in reports`\"](#expected-change-in-daily-cases), por \"probabilidade a posteriori de que $R_t < 1$\", referimo-nos especificamente à [área sob a curva da distribuição de probabilidade a posteriori](https://www.nature.com/articles/nmeth.3368/figures/1).\n\n:::\n\n## Distribuições de atraso e dados de casos\n### Dados de casos\n\nPara ilustrar as funções do `EpiNow2`, usaremos dados de surto do início da pandemia de COVID-19 no Reino Unido, considerando apenas os primeiros 90 dias observados. Os dados estão disponíveis no pacote R `{incidence2}`.\n\n::: {.callout-note title=\"No Brasil: de onde vêm as séries de casos\"}\n\nAs séries usadas neste tipo de análise saem dos sistemas de notificação: o **SINAN** para os\nagravos de notificação compulsória e o **SIVEP-Gripe** para casos e óbitos por SRAG. O SIVEP-Gripe\né o sistema oficial de registro da SRAG no país e tem base pública em [Portal de Dados Abertos do SUS — SIVEP-Gripe](https://dadosabertos.saude.gov.br/dataset/srag-2019-a-2026).\n\nDuas consequências práticas: os períodos mais recentes são **dados preliminares**, sujeitos a\nrevisão, e a consolidação leva tempo — é daí que vem a censura à direita nas últimas semanas da\nsérie. Fonte sobre a diferença entre dados preliminares e finais: [SINAN — instrucional para download de microdados](http://portalsinan.saude.gov.br/images/documentos/Agravos/microdados/INSTRUCIONAL_PARA_DOWNLOAD_DE_MICRODADOS_DO_SINAN.pdf).\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndplyr::as_tibble(incidence2::covidregionaldataUK)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6,370 × 13\n   date       region   region_code cases_new cases_total deaths_new deaths_total\n   <date>     <chr>    <chr>           <dbl>       <dbl>      <dbl>        <dbl>\n 1 2020-01-30 East Mi… E12000004          NA          NA         NA           NA\n 2 2020-01-30 East of… E12000006          NA          NA         NA           NA\n 3 2020-01-30 England  E92000001           2           2         NA           NA\n 4 2020-01-30 London   E12000007          NA          NA         NA           NA\n 5 2020-01-30 North E… E12000001          NA          NA         NA           NA\n 6 2020-01-30 North W… E12000002          NA          NA         NA           NA\n 7 2020-01-30 Norther… N92000002          NA          NA         NA           NA\n 8 2020-01-30 Scotland S92000003          NA          NA         NA           NA\n 9 2020-01-30 South E… E12000008          NA          NA         NA           NA\n10 2020-01-30 South W… E12000009          NA          NA         NA           NA\n# ℹ 6,360 more rows\n# ℹ 6 more variables: recovered_new <dbl>, recovered_total <dbl>,\n#   hosp_new <dbl>, hosp_total <dbl>, tested_new <dbl>, tested_total <dbl>\n```\n\n\n:::\n:::\n\n\nPara usar os dados, precisamos formatá-los para ter duas colunas:\n\n+ `date`: a data (como um objeto de data, veja `?is.Date()`),\n+ `confirm`: número de notificações da doença (confirm) nessa data.\n\nVamos usar o `{tidyr}` e o `{incidence2}` para isso:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncases_incidence <- incidence2::covidregionaldataUK %>%\n  tibble::as_tibble() %>%\n  # Pré-processar valores ausentes\n  tidyr::replace_na(base::list(cases_new = 0)) %>%\n  # Calcular a incidência diária\n  incidence2::incidence(\n    date_index = \"date\",\n    counts = \"cases_new\",\n    count_values_to = \"confirm\",\n    date_names_to = \"date\",\n    complete_dates = TRUE\n  )\n```\n:::\n\n\nCom `incidence2::incidence()`, agregamos casos em diferentes *intervalos* de tempo (isto é, dias, semanas ou meses) ou por categorias de *grupo*. Além disso, podemos obter datas completas para todo o intervalo de datas por categoria de grupo usando `complete_dates = TRUE`.\nExplore mais tarde o [manual de referência de `incidence2::incidence()`](https://www.reconverse.org/incidence2/manual.html#sec:man-incidence).\n\n::: {.callout-note title=\"Detalhes\" collapse=\"true\"}\n\n**Podemos reproduzir o {incidence2} com o {dplyr}?**\n\nPodemos obter um objeto semelhante a `cases` a partir do data frame `incidence2::covidregionaldataUK` usando o pacote `{dplyr}`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincidence2::covidregionaldataUK %>%\n  dplyr::select(date, cases_new) %>%\n  dplyr::group_by(date) %>%\n  dplyr::summarise(confirm = sum(cases_new, na.rm = TRUE)) %>%\n  dplyr::ungroup()\n```\n:::\n\n\nNo entanto, a função `incidence2::incidence()` contém argumentos convenientes, como `complete_dates`, que facilitam a obtenção de um objeto de incidência com o mesmo intervalo de datas para cada agrupamento, sem a necessidade de linhas de código extras ou de um pacote de séries temporais.\n\n:::\n\nVamos contextualizar este episódio no cenário de um **surto em andamento** com apenas os **primeiros 90 dias** de dados observados (escolhidos aqui para fins de ilustração, não como uma etapa obrigatória).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Supor que temos apenas os primeiros 90 dias desses dados\ncases_sliced <- cases_incidence %>%\n  dplyr::slice_head(n = 90)\n\nplot(cases_sliced)\n```\n\n::: {.cell-output-display}\n![](02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nPara passar as saídas do `{incidence2}` para o `{EpiNow2}`, precisamos remover uma coluna do objeto `cases_sliced`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remover coluna para atender ao formato de entrada do {EpiNow2}\ncases <- cases_sliced %>%\n  dplyr::select(-count_variable)\n\ncases\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 90 × 2\n   date       confirm\n   <date>       <dbl>\n 1 2020-01-30       3\n 2 2020-01-31       0\n 3 2020-02-01       0\n 4 2020-02-02       0\n 5 2020-02-03       0\n 6 2020-02-04       0\n 7 2020-02-05       2\n 8 2020-02-06       0\n 9 2020-02-07       0\n10 2020-02-08       8\n# ℹ 80 more rows\n```\n\n\n:::\n:::\n\n\n### Distribuições de atraso\n\nAssumimos que existem atrasos desde o momento da infecção até o momento em que um caso é notificado. Especificamos esses atrasos como distribuições para levar em conta a incerteza nas diferenças em nível individual. O atraso pode envolver múltiplos tipos de processos. Um atraso típico desde o momento da infecção até a notificação do caso pode consistir em:\n\n> **tempo da infecção até o início dos sintomas** (o [período de incubação](../glossario.qmd#incubation)) + **tempo do início dos sintomas até a notificação do caso** (o tempo de notificação).\n\nA distribuição de atraso para cada um desses processos pode ser estimada a partir de dados ou obtida da literatura. Podemos expressar a incerteza sobre os parâmetros corretos das distribuições assumindo que elas têm parâmetros **fixos** ou parâmetros **variáveis**. Para entender a diferença entre distribuições **fixas** e **variáveis**, vamos considerar o período de incubação.\n\n::: {.callout-note}\n\n### Atrasos e dados\nO número e o tipo de atraso são entradas flexíveis que dependem dos dados. Os exemplos abaixo destacam como os atrasos podem ser especificados para diferentes fontes de dados:\n\n<center>\n\n| Fonte de dados | Atraso(s) |\n| ------------- |-------------|\n| Momento do início dos sintomas | Período de incubação |\n| Momento da notificação do caso | Período de incubação + tempo do início dos sintomas até a notificação do caso |\n| Momento da internação | Período de incubação + tempo do início dos sintomas até a internação |\n\n</center>\n\n:::\n\n#### Distribuição do período de incubação\n\nA distribuição do período de incubação para muitas doenças geralmente pode ser obtida da literatura. O pacote `{epiparameter}` contém uma biblioteca de parâmetros epidemiológicos para diferentes doenças extraídos da literatura.\n\nEspecificamos uma distribuição gama (fixa) com média $\\mu = 4$ e desvio-padrão $\\sigma = 2$ (shape = $4$, scale = $1$) usando a função `Gamma()`, da seguinte forma:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincubation_period_fixed <- EpiNow2::Gamma(\n  mean = 4,\n  sd = 2,\n  max = 20\n)\n\nincubation_period_fixed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- gamma distribution (max: 20):\n  shape:\n    4\n  rate:\n    1\n```\n\n\n:::\n:::\n\n\nAqui você configura o período de incubação usando estatísticas resumo (`mean = 4`, `sd = 2`) como entrada, mas o `{EpiNow2}` converte esses valores nos parâmetros `shape` e `rate` de uma distribuição de probabilidade Gama e os imprime como saída. O argumento `max` é o valor máximo que a distribuição pode assumir; neste exemplo, 20 dias.\n\nPodemos plotar as distribuições geradas pelo `{EpiNow2}` usando `plot()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(incubation_period_fixed)\n```\n\n::: {.cell-output-display}\n![](02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note}\n\n### Por que uma distribuição gama?\n\nO período de incubação deve ser um valor positivo. Portanto, devemos especificar uma distribuição no `{EpiNow2}` restrita apenas a valores positivos.\n\n`Gamma()` dá suporte a distribuições Gama e `LogNormal()` a distribuições Log-normal, que são distribuições exclusivas para valores positivos.\n\nPara todos os tipos de atraso, precisaremos usar distribuições restritas a valores positivos — não queremos incluir atrasos com dias negativos em nossa análise!\n\n:::\n\n#### Incluindo a incerteza da distribuição\n\nPara especificar uma distribuição **variável**, incluímos incerteza em torno da média $\\mu$ e do desvio-padrão $\\sigma$ de nossa distribuição gama. Se a nossa distribuição do período de incubação tem média $\\mu$ e desvio-padrão $\\sigma$, podemos assumir que a média ($\\mu$) segue uma distribuição Normal com desvio-padrão $\\sigma_{\\mu}$:\n\n$$\\mbox{Normal}(\\mu,\\sigma_{\\mu}^2)$$\n\ne o desvio-padrão ($\\sigma$) segue uma distribuição Normal com desvio-padrão $\\sigma_{\\sigma}$:\n\n$$\\mbox{Normal}(\\sigma,\\sigma_{\\sigma}^2).$$\n\nEspecificamos isso usando `Normal()` para cada argumento: a média ($\\mu = 4$ com $\\sigma_{\\mu} = 0.5$) e o desvio-padrão ($\\sigma = 2$ com $\\sigma_{\\sigma} = 0.5$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincubation_period_variable <- EpiNow2::Gamma(\n  mean = EpiNow2::Normal(mean = 4, sd = 0.5),\n  sd = EpiNow2::Normal(mean = 2, sd = 0.5),\n  max = 20\n)\n\nincubation_period_variable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- gamma distribution (max: 20):\n  shape:\n    - normal distribution:\n      mean:\n        4\n      sd:\n        0.61\n  rate:\n    - normal distribution:\n      mean:\n        1\n      sd:\n        0.31\n```\n\n\n:::\n:::\n\n\nVamos plotar a distribuição que acabamos de configurar:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(incubation_period_variable)\n```\n\n::: {.cell-output-display}\n![](02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"Checklist\"}\n\nPreferimos adicionar incerteza a cada estimativa pontual sempre que disponível. As boas práticas no relato de distribuições de atraso epidemiológicas recomendam incluir estimativas de incerteza, pois isso pode impactar a modelagem subsequente e sinalizar que mais dados são necessários ([Charniga et al., 2024](https://doi.org/10.1371/journal.pcbi.1012520)).\n\n:::\n\n#### Atrasos de notificação\n\nApós o período de incubação, haverá um atraso de tempo adicional entre o início dos sintomas e a notificação do caso: o atraso de notificação. Podemos especificar isso como uma distribuição fixa ou variável, ou estimar uma distribuição a partir dos dados.\n\nAo especificar uma distribuição, é útil visualizar a densidade de probabilidade para observar o pico e a dispersão da distribuição; neste caso, usaremos uma distribuição *log-normal*.\n\nSe quisermos assumir que o atraso médio de notificação é de 2 dias (com uma incerteza de 0,5 dia) e um desvio-padrão de 1 dia (com incerteza de 0,5 dia), podemos especificar uma distribuição variável usando `LogNormal()` como fizemos antes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreporting_delay_variable <- EpiNow2::LogNormal(\n  mean = EpiNow2::Normal(mean = 2, sd = 0.5),\n  sd = EpiNow2::Normal(mean = 1, sd = 0.5),\n  max = 10\n)\n```\n:::\n\n\n::: {.callout-note title=\"Detalhes\" collapse=\"true\"}\n\n**Como obter o atraso de notificação a partir dos dados?**\n\nSe houver dados disponíveis sobre o tempo entre o início dos sintomas e a notificação, podemos usar a função `EpiNow2::estimate_delay()` para estimar uma distribuição log-normal a partir de um vetor de atrasos.\n\nO código abaixo ilustra como usar `EpiNow2::estimate_delay()` com dados sintéticos de ebola. Calculamos o atraso de notificação para cada caso como a diferença de tempo **da** data de início dos sintomas **até** a data de internação (data em que o caso foi notificado).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n# Etapas:\n# - obter dados de ebola do pacote {outbreaks}\n# - manter um subconjunto de colunas apenas para este exemplo\n# - calcular a diferença de tempo entre duas datas na linelist\n# - extrair a diferença de tempo como um objeto da classe vector\n# - estimar os parâmetros de atraso usando {EpiNow2}\n\noutbreaks::ebola_sim_clean$linelist %>%\n  tibble::as_tibble() %>%\n  dplyr::select(case_id, date_of_onset, date_of_hospitalisation) %>%\n  dplyr::mutate(reporting_delay = date_of_hospitalisation - date_of_onset) %>%\n  dplyr::pull(reporting_delay) %>%\n  EpiNow2::estimate_delay(\n    samples = 1000,\n    bootstraps = 10\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- lognormal distribution (max: 22):\n  meanlog:\n    - normal distribution:\n      mean:\n        0.23\n      sd:\n        0.11\n  sdlog:\n    - normal distribution:\n      mean:\n        0.96\n      sd:\n        0.099\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Tempo de geração\n\nComo apresentamos no [episódio anterior deste tutorial](01-acessar-atrasos.qmd), também precisamos especificar uma distribuição para o tempo de geração. Aqui usaremos uma distribuição log-normal com média de 3,6 e desvio-padrão de 3,1 ([Ganyani et al. 2020](https://doi.org/10.2807/1560-7917.ES.2020.25.17.2000257)).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeneration_time_variable <- EpiNow2::LogNormal(\n  mean = EpiNow2::Normal(mean = 3.6, sd = 0.5),\n  sd = EpiNow2::Normal(mean = 3.1, sd = 0.5),\n  max = 20\n)\n```\n:::\n\n\n::: {.callout-note title=\"Checklist\"}\n\nAgora temos as distribuições necessárias para quantificar a transmissão a partir de notificações de casos usando o `{EpiNow2}`:\n\n- **Tempo de geração**: tempo entre o início da infecciosidade em um caso primário (índice) e em seu caso secundário.\n- **Atrasos**: tempo da infecção até a notificação do caso (período de incubação + atraso de notificação).\n\n```r\ngeneration_time_variable\nincubation_period_variable\nreporting_delay_variable\n```\n\n:::\n\n::: {.callout-note title=\"Para se aprofundar\"}\n\nObserve que podemos configurar estatísticas resumo (por exemplo, `mean`, `sd`) como entrada para `EpiNow2::LogNormal()` ou `EpiNow2::Gamma()`, mas o `{EpiNow2}` sempre as converterá para parâmetros da distribuição de probabilidade: `shape` e `scale` para Gamma, `meanlog` e `sdlog` para LogNormal.\n\nQuando possível, preferimos especificar diretamente os parâmetros \"naturais\" da distribuição (como `shape` e `rate` para Gamma, `meanlog` e `sdlog` para LogNormal), em vez de depender da conversão média/desvio-padrão, pois isso evita ambiguidades e proporciona um controle mais preciso sobre a distribuição resultante.\n\n:::\n\n::: {.callout-tip .desafio title=\"Desafio\"}\n\nUsando o período de incubação do sarampo do pacote `{epiparameter}`, adapte essa saída à interface de distribuição do `{EpiNow2}`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeasles_incubation <- epiparameter::epiparameter_db(\n  disease = \"Measles\",\n  epi_name = \"incubation\",\n  single_epiparameter = TRUE\n)\n```\n:::\n\n\n::: {.callout-note title=\"Dica\" collapse=\"true\"}\n\nUse estas perguntas como guia:\n\n- O tempo de incubação segue uma distribuição LogNormal ou Gamma?\n- Quais são os *parâmetros da distribuição* do tempo de incubação?\n- Com base nessa distribuição, qual função devemos usar: `EpiNow2::LogNormal()` ou `EpiNow2::Gamma()`?\n- Qual poderia ser o número máximo de dias para essa distribuição? Observe isso a partir de um gráfico.\n\nVocê pode copiar e colar os valores dos parâmetros correspondentes diretamente da saída do `{epiparameter}` na entrada do `{EpiNow2}`.\n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\nVamos imprimir a saída:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeasles_incubation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDisease: Measles\nPathogen: Measles Virus\nEpi Parameter: incubation period\nStudy: Lessler J, Reich N, Brookmeyer R, Perl T, Nelson K, Cummings D (2009).\n\"Incubation periods of acute respiratory viral infections: a systematic\nreview.\" _The Lancet Infectious Diseases_.\ndoi:10.1016/S1473-3099(09)70069-12\n<https://doi.org/10.1016/S1473-3099%2809%2970069-12>.\nDistribution: lnorm (days)\nParameters:\n  meanlog: 2.526\n  sdlog: 0.207\n```\n\n\n:::\n:::\n\n\nEla segue uma distribuição Log-normal (`lnorm`), com os parâmetros: `meanlog` e `sdlog`; portanto, a função correspondente é `EpiNow2::LogNormal()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(measles_incubation, xlim = c(0, 25))\n```\n\n::: {.cell-output-display}\n![](02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nA partir do gráfico, um valor máximo plausível para o período de incubação seria de 20 dias.\n\nEm seguida, nossa chamada da função do EpiNow2 fica assim:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeasles_incubation_epinow <- EpiNow2::LogNormal(\n  meanlog = 2.526,\n  sdlog = 0.207,\n  max = 20\n)\n\nmeasles_incubation_epinow\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- lognormal distribution (max: 20):\n  meanlog:\n    2.5\n  sdlog:\n    0.21\n```\n\n\n:::\n:::\n\n\nOu `epiparameter::get_parameters(measles_incubation)` para reutilizar os parâmetros diretamente.\n\nO gráfico gerado pelo {EpiNow2} é:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(measles_incubation_epinow)\n```\n\n::: {.cell-output-display}\n![](02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nObserve que se esquecermos de definir um valor máximo, obteremos um erro nesta etapa.\n\n:::\n\n:::\n\n## Obtenção das estimativas\n\nA função `epinow()` é um wrapper para a função `estimate_infections()`, usada para estimar casos por data de infecção. A distribuição do tempo de geração e as distribuições de atraso devem ser fornecidas usando as funções `generation_time_opts()` e `delay_opts()`, respectivamente.\n\nExistem muitas outras entradas que podem ser passadas para `epinow()`; consulte `?EpiNow2::epinow()` para mais detalhes.\nUma entrada opcional é especificar uma priori *log-normal* para o número de reprodução efetivo $R_t$ no início do surto. Especificamos uma média de 2 e desvio-padrão de 2 como argumentos de `prior` dentro de `rt_opts()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# definir a distribuição a priori de Rt\nrt_prior <- EpiNow2::rt_opts(prior = EpiNow2::LogNormal(mean = 2, sd = 2))\n```\n:::\n\n\n::: {.callout-note}\n\n### Inferência bayesiana usando o Stan\n\nA inferência bayesiana é realizada usando métodos MCMC com o programa [Stan](https://mc-stan.org/). Há uma série de configurações padrão para as funções do Stan, incluindo o número de cadeias e o número de amostras por cadeia (veja `?EpiNow2::stan_opts()`).\n\nPara reduzir o tempo de computação, podemos executar as cadeias em paralelo. Para fazer isso, devemos definir o número de núcleos a serem utilizados. Por padrão, 4 cadeias MCMC são executadas (veja `EpiNow2::stan_opts()$chains`), de modo que podemos definir um número igual de núcleos para serem usados em paralelo da seguinte forma:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithr::local_options(base::list(mc.cores = 4))\n```\n:::\n\n\nPara descobrir o número máximo de núcleos disponíveis na sua máquina, use `parallel::detectCores()`.\nSe tiver menos de 4, você pode substituir `mc.cores = 4` por `mc.cores = parallel::detectCores() - 1`.\n\n:::\n\n::: {.callout-note title=\"Checklist\"}\n\n**Nota:** no código abaixo, são usadas as distribuições `*_fixed` em vez de `*_variable` (distribuições de atraso com incerteza). Isso serve para acelerar o tempo de computação. De modo geral, recomenda-se usar distribuições variáveis que levem em conta a incerteza adicional.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# alternativas fixas\ngeneration_time_fixed <- EpiNow2::LogNormal(\n  mean = 3.6,\n  sd = 3.1,\n  max = 20\n)\n\nreporting_delay_fixed <- EpiNow2::LogNormal(\n  mean = 2,\n  sd = 1,\n  max = 10\n)\n```\n:::\n\n\n:::\n\nAgora você está pronto para executar `EpiNow2::epinow()` para estimar o número de reprodução variante no tempo para os primeiros 90 dias:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimates <- EpiNow2::epinow(\n  # casos notificados\n  data = cases,\n  # atrasos\n  generation_time = EpiNow2::generation_time_opts(generation_time_fixed),\n  delays = EpiNow2::delay_opts(incubation_period_fixed + reporting_delay_fixed),\n  # priori\n  rt = rt_prior\n)\n```\n:::\n\n\n<!-- ```{r, message = FALSE,warning=FALSE, eval = TRUE, echo=FALSE} -->\n<!-- estimates <- EpiNow2::epinow( -->\n<!--   # reported cases -->\n<!--   data = cases, -->\n<!--   # delays -->\n<!--   generation_time = EpiNow2::generation_time_opts(generation_time_fixed), -->\n<!--   delays = EpiNow2::delay_opts(incubation_period_fixed + reporting_delay_fixed), -->\n<!--   # prior -->\n<!--   rt = rt_prior, -->\n<!--   stan = EpiNow2::stan_opts(method = \"vb\") -->\n<!-- ) -->\n<!-- ``` -->\n\n::: {.callout-note}\n\n### Não espere a conclusão disto para continuar\n\nPara o propósito deste tutorial, podemos opcionalmente usar `EpiNow2::stan_opts()` para reduzir o tempo de computação. Podemos especificar um número fixo de `samples = 1000` e `chains = 2` no argumento `stan` da função `EpiNow2::epinow()`. Esperamos que isso leve aproximadamente 3 minutos.\n\n<!-- We can optionally set `stan = stan_opts(method = \"vb\")` to use an approximate sampling method. We expect this to take less than 1 minute. -->\n\n```r\n# você pode adicionar o argumento `stan`\nEpiNow2::epinow(\n  ...,\n  stan = EpiNow2::stan_opts(samples = 1000, chains = 2)\n)\n```\n\n**Lembre-se:** usar um número adequado de *samples* (amostras) e *chains* (cadeias) é crucial para garantir a convergência e obter estimativas confiáveis em computações bayesianas usando o Stan. Saídas mais precisas têm como contrapartida um tempo de processamento maior.\n\n:::\n\n### Resultados\n\nPodemos extrair e visualizar as estimativas do número de reprodução efetivo ao longo do tempo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(estimates, type = \"R\")\n```\n\n::: {.cell-output-display}\n![](02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nA incerteza nas estimativas aumenta ao longo do tempo. Isso ocorre porque as estimativas são orientadas por dados do passado — dentro dos períodos de atraso.\n\nO gráfico distingue três categorias:\n\n- **Estimate** (verde) usa todos os dados disponíveis;\n- **Estimate based on partial data** (laranja) baseia-se em menos dados (porque as infecções em torno desse período têm maior probabilidade de ainda não terem sido observadas) e, portanto, apresenta intervalos progressivamente mais amplos em direção à data do último ponto de dados; e\n- **Forecast** (roxo) é uma projeção para o futuro.\n\nTambém podemos visualizar a estimativa da taxa de crescimento ao longo do tempo:\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(estimates, type = \"growth_rate\")\n```\n\n::: {.cell-output-display}\n![](02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nPara extrair um resumo das principais métricas de transmissão na *data mais recente* dos dados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(estimates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        measure              estimate\n                         <char>                <char>\n1:       New infections per day 9094 (4896 -- 122233)\n2:   Expected change in reports                Stable\n3:   Effective reproduction no.       1 (0.76 -- 1.4)\n4:               Rate of growth  0.01 (-0.095 -- 0.1)\n5: Doubling/halving time (days)      69 (6.6 -- -7.3)\n```\n\n\n:::\n:::\n\n\nComo essas estimativas são baseadas em dados parciais, elas têm um amplo intervalo de incerteza.\n\n+ A partir do resumo de nossa análise, vemos que a mudança esperada nas notificações é Stable com novas infecções estimadas em 9094 (4896 -- 122233).\n\n+ A estimativa do número de reprodução efetivo $R_t$ (na última data dos dados) é 1 (0.76 -- 1.4).\n\n+ A taxa de crescimento exponencial do número de casos é 0.01 (-0.095 -- 0.1).\n\n+ O tempo de duplicação (o tempo necessário para o número de casos dobrar) é 69 (6.6 -- -7.3).\n\n::: {.callout-note}\n\n### `Expected change in reports`\n\nUm fator que descreve a mudança esperada nas notificações com base na probabilidade a posteriori de que $R_t < 1$.\n\n<center>\n| Probabilidade ($p$) | Mudança esperada |\n| ------------- |-------------|\n|$p < 0.05$ | Aumentando (*Increasing*) |\n|$0.05 \\leq p< 0.4$ | Provavelmente aumentando (*Likely increasing*) |\n|$0.4 \\leq p< 0.6$ | Estável (*Stable*) |\n|$0.6 \\leq p < 0.95$ | Provavelmente diminuindo (*Likely decreasing*) |\n|$0.95 \\leq p \\leq 1$ | Diminuindo (*Decreasing*) |\n</center>\n\n:::\n\n::: {.callout-note}\n\n### Intervalos de credibilidade\n\nEm todas as figuras de saída do `{EpiNow2}`, as regiões sombreadas refletem intervalos de credibilidade de 90%, 50% e 20%, ordenados do mais claro ao mais escuro.\n\n:::\n\n::: {.callout-tip .desafio title=\"Desafio\"}\n\nNa saída de `plot(estimates, type = \"R\")`, qual parâmetro de entrada delimita a extensão da trajetória com a categoria `Estimate based on parial data` (laranja)?\n\n::: {.callout-note title=\"Dica\" collapse=\"true\"}\n\nComo explicamos acima, as infecções em torno desse período têm maior probabilidade de ainda não terem sido observadas. Portanto, o parâmetro de entrada deve informar a probabilidade de observar novas infecções.\n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\nO valor máximo finito da distribuição do *tempo de geração* define o intervalo de `Estimate based on parial data`.\nO *tempo de geração* foi configurado com um valor máximo de 20 dias.\n\n:::\n\n:::\n\n::: {.callout-note title=\"Checklist\"}\n\nO `{EpiNow2}` pode ser usado para estimar métricas de transmissão a partir de dados de casos em qualquer momento durante o curso de um surto. A confiabilidade dessas estimativas depende da qualidade dos dados e da escolha apropriada das distribuições de atraso.\n\nPara reutilizar diretamente os atrasos armazenados no `{epiparameter}`, leia o próximo tutorial sobre [usar distribuições de atraso na análise](03-funcoes-de-atraso.qmd).\n\nPara aprender a criar previsões e explorar algumas das opções adicionais de inferência disponíveis no `{EpiNow2}`, leia o tutorial seguinte sobre [criar previsões de curto prazo](04-criar-previsoes.qmd).\n\n:::\n\n::: {.callout-note title=\"Discussão\"}\n\n### Como o {EpiNow2} funciona?\n\nO {EpiNow2} contém diferentes modelos sobre como as infecções surgem.\nUm dos principais modelos usados na configuração padrão é o **modelo da equação de renovação**.\nSe você quiser se familiarizar com ele e aprender como os atrasos são levados em conta na estimativa de $R_t$,\nvocê pode ler o episódio sobre\n[Introdução à equação de renovação](../notas/equacao-de-renovacao.qmd)\nna seção \"Mais recursos\" do site deste tutorial.\n\n:::\n\n## Desafio\n\n::: {.callout-tip .desafio title=\"Desafio\"}\n\n**Quantificar a heterogeneidade geográfica**\n\nOs dados de surto do início da pandemia de COVID-19 no Reino Unido provenientes do pacote R `{incidence2}` incluem a região em que os casos foram registrados. Para encontrar estimativas regionais do número de reprodução efetivo e de casos, devemos formatar os dados para que tenham três colunas:\n\n+ `date`: a data,\n+ `region`: a região,\n+ `confirm`: número de notificações da doença (confirm) para uma região em uma determinada data.\n\nGere estimativas regionais de Rt a partir do data frame `incidence2::covidregionaldataUK`:\n\n- use o `{incidence2}` para converter os dados agregados em dados de incidência pela variável `region`,\n- mantenha as primeiras 90 datas para todas as regiões,\n- estime o Rt por região usando o tempo de geração e os atrasos definidos neste episódio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregional_cases <- incidence2::covidregionaldataUK %>%\n  # usar o {tidyr} para pré-processar valores ausentes\n  tidyr::replace_na(base::list(cases_new = 0))\n```\n:::\n\n\n::: {.callout-note title=\"Dica\" collapse=\"true\"}\n\nPara manipular os dados, você pode:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregional_cases <- incidence2::covidregionaldataUK %>%\n  # usar o {tidyr} para pré-processar valores ausentes\n  tidyr::replace_na(base::list(cases_new = 0)) %>%\n  # usar o {incidence2} para converter dados agregados em dados de incidência\n  incidence2::incidence(\n    date_index = \"date\",\n    groups = \"region\",\n    counts = \"cases_new\",\n    count_values_to = \"confirm\",\n    date_names_to = \"date\",\n    complete_dates = TRUE\n  ) %>%\n  dplyr::select(-count_variable) %>%\n  dplyr::filter(date < ymd(20200301))\n```\n:::\n\n\nPara aprender como realizar a estimação regional de Rt, leia a seção sobre `regional_epinow()` na vinheta Get started em <https://epiforecasts.io/EpiNow2/articles/EpiNow2.html#regional_epinow>\n\n:::\n\n::: {.callout-note .solucao title=\"Solução\" collapse=\"true\"}\n\nPara encontrar estimativas regionais, usamos as mesmas entradas de `epinow()` na função `regional_epinow()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimates_regional <- EpiNow2::regional_epinow(\n  # casos\n  data = regional_cases,\n  # atrasos\n  generation_time = EpiNow2::generation_time_opts(generation_time_fixed),\n  delays = EpiNow2::delay_opts(incubation_period_fixed + reporting_delay_fixed),\n  # priori\n  rt = rt_prior\n)\n```\n:::\n\n\nPlote os resultados com:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimates_regional$summary$summarised_results$table\n\nestimates_regional$summary$plots$R\n```\n:::\n\n\n![](../img/quantify-transmissibility-regional.png)\n\n:::\n\n:::\n\n<!-- :::::::::::::::::::::::::: testimonial -->\n\n<!-- ### the i2extras package -->\n\n<!-- `{i2extras}` package also estimate transmission metrics like growth rate and doubling/halving time at different time intervals (i.e., days, weeks, or months). `{i2extras}` require `{incidence2}` objects as inputs. Read further in its [Fitting curves](https://www.reconverse.org/i2extras/articles/fitting_epicurves.html) vignette. -->\n\n<!-- :::::::::::::::::::::::::: -->\n\n::: {.callout-note title=\"Pontos-chave\"}\n\n- Métricas de transmissão podem ser estimadas a partir de dados de casos após levar em conta os atrasos\n- A incerteza pode ser incorporada nas distribuições de atraso\n\n:::\n",
    "supporting": [
      "02-quantificar-transmissibilidade_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}