<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quantificar a transmissibilidade – Análise em tempo real e previsão para surtos com R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../episodios/03-funcoes-de-atraso.html" rel="next">
<link href="../episodios/01-acessar-atrasos.html" rel="prev">
<link href="../img/pkgs-hexlogos.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4f8723c4e91b4923163491bd987d7814.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../episodios/02-quantificar-transmissibilidade.html"><span class="chapter-title">Quantificar a transmissibilidade</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Análise em tempo real e previsão para surtos com R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/MVMLima/tutorials-middle-pt" title="Código fonte" class="quarto-navigation-tool px-1" aria-label="Código fonte"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Compartilhar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Compartilhar"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Análise em tempo real e previsão para surtos com R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../setup.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Configuração</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../episodios/01-acessar-atrasos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Acessar distribuições de atraso epidemiológicas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../episodios/02-quantificar-transmissibilidade.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Quantificar a transmissibilidade</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../episodios/03-funcoes-de-atraso.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Usar distribuições de atraso na análise</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../episodios/04-criar-previsoes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Criar previsão de curto prazo</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../episodios/05-severidade-estatica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Estimativa da gravidade de um surto</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../episodios/06-superspreading-estimar.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Levar em conta o superspreading</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../episodios/07-superspreading-simular.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Simular cadeias de transmissão</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apêndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notas/equacao-de-renovacao.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introdução à equação de renovação</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notas/ajuste-cfr-atrasos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Como ajustar o CFR pelo atraso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../perfis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Para quem são estes tutoriais</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../glossario.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Glossário de termos: Epiverse-TRACE</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../instrutor.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Notas para quem conduz a oficina</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../licenca.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Licença e créditos</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução">Introdução</a></li>
  <li><a href="#distribuições-de-atraso-e-dados-de-casos" id="toc-distribuições-de-atraso-e-dados-de-casos" class="nav-link" data-scroll-target="#distribuições-de-atraso-e-dados-de-casos">Distribuições de atraso e dados de casos</a>
  <ul class="collapse">
  <li><a href="#dados-de-casos" id="toc-dados-de-casos" class="nav-link" data-scroll-target="#dados-de-casos">Dados de casos</a></li>
  <li><a href="#distribuições-de-atraso" id="toc-distribuições-de-atraso" class="nav-link" data-scroll-target="#distribuições-de-atraso">Distribuições de atraso</a></li>
  </ul></li>
  <li><a href="#obtenção-das-estimativas" id="toc-obtenção-das-estimativas" class="nav-link" data-scroll-target="#obtenção-das-estimativas">Obtenção das estimativas</a>
  <ul class="collapse">
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados">Resultados</a></li>
  </ul></li>
  <li><a href="#desafio" id="toc-desafio" class="nav-link" data-scroll-target="#desafio">Desafio</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/MVMLima/tutorials-middle-pt/edit/main/episodios/02-quantificar-transmissibilidade.qmd" class="toc-action"><i class="bi bi-github"></i>Editar essa página</a></li><li><a href="https://github.com/MVMLima/tutorials-middle-pt/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Quantificar a transmissibilidade</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="Perguntas">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Perguntas
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Como posso estimar o número de reprodução variante no tempo (<span class="math inline">\(R_t\)</span>) e a taxa de crescimento a partir de uma série temporal de dados de casos?</li>
<li>Como posso quantificar a heterogeneidade geográfica a partir dessas métricas de transmissão?</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Objetivos">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Objetivos
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Aprender a estimar métricas de transmissão a partir de uma série temporal de dados de casos usando o pacote R <code>{EpiNow2}</code></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Pré-requisitos">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Pré-requisitos
</div>
</div>
<section id="pré-requisitos" class="level2 callout-body-container callout-body">
<h2 class="anchored" data-anchor-id="pré-requisitos">Pré-requisitos</h2>
<p>Você deve se familiarizar com os seguintes conceitos antes de trabalhar neste tutorial:</p>
<p><strong>Estatística</strong>: <a href="https://epiverse-trace.github.io/tutorials/">distribuições de probabilidade</a>, princípios de análise bayesiana.</p>
<p><strong>Teoria epidêmica</strong>: <a href="../episodios/01-acessar-atrasos.html">Tempo de geração</a>, número de reprodução efetivo.</p>
<p><strong>Ciência de dados</strong>: transformação e visualização de dados. Você pode revisar o episódio sobre <a href="https://epiverse-trace.github.io/tutorials-early/aggreagate-visualize.html">agregar e visualizar</a> dados de incidência.</p>
<p><strong>Pacotes R instalados</strong>: <code>{EpiNow2}</code>, <code>{incidence2}</code>, <code>{tidyverse}</code>.</p>
</section>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Detalhes">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Detalhes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Instale os pacotes se eles ainda não estiverem instalados (se desejar, você pode configurar o espelho brasileiro do CRAN com <code>options(repos = c(CRAN = "https://cran-r.c3sl.ufpr.br/"))</code>):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span>base<span class="sc">::</span><span class="fu">require</span>(<span class="st">"pak"</span>)) <span class="fu">install.packages</span>(<span class="st">"pak"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pak<span class="sc">::</span><span class="fu">pak</span>(<span class="fu">c</span>(<span class="st">"EpiNow2"</span>, <span class="st">"incidence2"</span>, <span class="st">"tidyverse"</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<p>Se você receber alguma mensagem de erro, acesse a <a href="../setup.html#software-setup">página principal de configuração</a>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lembrete: o número de reprodução efetivo, <span class="math inline">\(R_t\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>O <a href="../glossario.html#basic">número de reprodução básico</a>, <span class="math inline">\(R_0\)</span>, é o número médio de casos causados por um indivíduo infeccioso em uma população totalmente suscetível.</p>
<p>Mas em um surto em andamento, a população não permanece totalmente suscetível, pois aqueles que se recuperam da infecção geralmente adquirem imunidade. Além disso, podem ocorrer mudanças no comportamento ou outros fatores que afetam a transmissão.</p>
<p>Quando temos interesse em monitorar as mudanças na transmissão, estamos mais interessados no valor do <strong>número de reprodução efetivo</strong>, <span class="math inline">\(R_t\)</span>, que representa o número médio de casos causados por um indivíduo infeccioso na população no tempo <span class="math inline">\(t\)</span>, dado o estado atual da população (incluindo níveis de imunidade e medidas de controle).</p>
</div>
</div>
<section id="introdução" class="level2">
<h2 class="anchored" data-anchor-id="introdução">Introdução</h2>
<p>A intensidade de transmissão de um surto é quantificada usando duas métricas fundamentais: o número de reprodução, que informa sobre a força da transmissão ao indicar quantos novos casos são esperados a partir de cada caso existente; e a <a href="../glossario.html#growth">taxa de crescimento</a>, que informa sobre a velocidade da transmissão ao indicar a rapidez com que o surto está se propagando ou diminuindo (tempo de duplicação/tempo de redução pela metade) em uma população. Para mais detalhes sobre a distinção entre velocidade e força de transmissão e suas implicações para o controle, consulte <a href="https://royalsocietypublishing.org/doi/full/10.1098/rspb.2020.1556">Dushoff &amp; Park, 2021</a>.</p>
<p>Para estimar essas métricas fundamentais usando dados de casos, precisamos levar em conta os atrasos entre a data das infecções e a data dos casos notificados. Em uma situação de surto, os dados geralmente estão disponíveis apenas por datas de notificação; portanto, devemos usar métodos de estimação para corrigir para esses atrasos ao tentar entender as mudanças na transmissão ao longo do tempo.</p>
<p>Nos próximos tutoriais, nosso foco será em como usar as funções do <code>{EpiNow2}</code> para estimar métricas de transmissão a partir de dados de casos. Não abordaremos a fundamentação teórica dos modelos ou da estrutura de inferência; para detalhes sobre esses conceitos, consulte a <a href="https://epiforecasts.io/EpiNow2/dev/articles/estimate_infections.html">vinheta</a>.</p>
<p>Neste tutorial, aprenderemos a usar o pacote <code>{EpiNow2}</code> para estimar o número de reprodução variante no tempo. Obteremos os dados de entrada do <code>{incidence2}</code>. Usaremos os pacotes <code>{tidyr}</code> e <code>{dplyr}</code> para organizar algumas de suas saídas, o <code>{ggplot2}</code> para visualizar a distribuição dos casos e o operador pipe <code>%&gt;%</code> para encadear algumas de suas funções; portanto, vamos carregar também o pacote <code>{tidyverse}</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EpiNow2)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(incidence2)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="Checklist">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Checklist
</div>
</div>
<section id="os-dois-pontos-duplos" class="level3 callout-body-container callout-body">
<h3 class="anchored" data-anchor-id="os-dois-pontos-duplos">Os dois-pontos duplos</h3>
<p>Os dois-pontos duplos <code>::</code> no R permitem chamar uma função específica de um pacote sem carregar o pacote inteiro no ambiente atual.</p>
<p>Por exemplo, <code>dplyr::filter(data, condition)</code> usa <code>filter()</code> do pacote <code>{dplyr}</code>.</p>
<p>Isso nos ajuda a lembrar as funções dos pacotes e a evitar conflitos de namespace.</p>
</section>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Para o instrutor">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Para o instrutor
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Este tutorial ilustra o uso de <code>epinow()</code> para estimar o número de reprodução variante no tempo e os momentos de infecção. As pessoas participantes devem compreender as entradas necessárias para o modelo e as limitações das saídas geradas.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Inferência bayesiana
</div>
</div>
<div class="callout-body-container callout-body">
<p>O pacote R <code>EpiNow2</code> usa uma estrutura de <a href="../glossario.html#bayesian">inferência bayesiana</a> para estimar números de reprodução e momentos de infecção com base nas datas de notificação. Em outras palavras, ele estima a transmissão com base em quando as pessoas foram efetivamente infectadas (em vez do início dos sintomas), levando em conta os atrasos nos dados observados. Em contrapartida, o pacote <code>{EpiEstim}</code> permite uma estimação em tempo real mais rápida e simples do número de reprodução usando apenas dados de casos ao longo do tempo, refletindo como a transmissão varia com base em quando os sintomas aparecem.</p>
<p>Na inferência bayesiana, usamos o conhecimento a priori (distribuições a priori) com os dados (em uma função de verossimilhança) para encontrar a probabilidade a posteriori:</p>
<p><span class="math inline">\(Posterior \, probability \propto likelihood \times prior \, probability\)</span></p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Para o instrutor">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Para o instrutor
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Faça referência à distribuição de probabilidade a priori e à distribuição de <a href="https://en.wikipedia.org/wiki/Posterior_probability">probabilidade a posteriori</a>.</p>
<p>No <a href="#expected-change-in-daily-cases">callout “<code>Expected change in reports</code>”</a>, por “probabilidade a posteriori de que <span class="math inline">\(R_t &lt; 1\)</span>”, referimo-nos especificamente à <a href="https://www.nature.com/articles/nmeth.3368/figures/1">área sob a curva da distribuição de probabilidade a posteriori</a>.</p>
</div>
</div>
</div>
</section>
<section id="distribuições-de-atraso-e-dados-de-casos" class="level2">
<h2 class="anchored" data-anchor-id="distribuições-de-atraso-e-dados-de-casos">Distribuições de atraso e dados de casos</h2>
<section id="dados-de-casos" class="level3">
<h3 class="anchored" data-anchor-id="dados-de-casos">Dados de casos</h3>
<p>Para ilustrar as funções do <code>EpiNow2</code>, usaremos dados de surto do início da pandemia de COVID-19 no Reino Unido, considerando apenas os primeiros 90 dias observados. Os dados estão disponíveis no pacote R <code>{incidence2}</code>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="No Brasil: de onde vêm as séries de casos">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>No Brasil: de onde vêm as séries de casos
</div>
</div>
<div class="callout-body-container callout-body">
<p>As séries usadas neste tipo de análise saem dos sistemas de notificação: o <strong>SINAN</strong> para os agravos de notificação compulsória e o <strong>SIVEP-Gripe</strong> para casos e óbitos por SRAG. O SIVEP-Gripe é o sistema oficial de registro da SRAG no país e tem base pública em <a href="https://dadosabertos.saude.gov.br/dataset/srag-2019-a-2026">Portal de Dados Abertos do SUS — SIVEP-Gripe</a>.</p>
<p>Duas consequências práticas: os períodos mais recentes são <strong>dados preliminares</strong>, sujeitos a revisão, e a consolidação leva tempo — é daí que vem a censura à direita nas últimas semanas da série. Fonte sobre a diferença entre dados preliminares e finais: <a href="http://portalsinan.saude.gov.br/images/documentos/Agravos/microdados/INSTRUCIONAL_PARA_DOWNLOAD_DE_MICRODADOS_DO_SINAN.pdf">SINAN — instrucional para download de microdados</a>.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">as_tibble</span>(incidence2<span class="sc">::</span>covidregionaldataUK)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,370 × 13
   date       region   region_code cases_new cases_total deaths_new deaths_total
   &lt;date&gt;     &lt;chr&gt;    &lt;chr&gt;           &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;
 1 2020-01-30 East Mi… E12000004          NA          NA         NA           NA
 2 2020-01-30 East of… E12000006          NA          NA         NA           NA
 3 2020-01-30 England  E92000001           2           2         NA           NA
 4 2020-01-30 London   E12000007          NA          NA         NA           NA
 5 2020-01-30 North E… E12000001          NA          NA         NA           NA
 6 2020-01-30 North W… E12000002          NA          NA         NA           NA
 7 2020-01-30 Norther… N92000002          NA          NA         NA           NA
 8 2020-01-30 Scotland S92000003          NA          NA         NA           NA
 9 2020-01-30 South E… E12000008          NA          NA         NA           NA
10 2020-01-30 South W… E12000009          NA          NA         NA           NA
# ℹ 6,360 more rows
# ℹ 6 more variables: recovered_new &lt;dbl&gt;, recovered_total &lt;dbl&gt;,
#   hosp_new &lt;dbl&gt;, hosp_total &lt;dbl&gt;, tested_new &lt;dbl&gt;, tested_total &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Para usar os dados, precisamos formatá-los para ter duas colunas:</p>
<ul>
<li><code>date</code>: a data (como um objeto de data, veja <code>?is.Date()</code>),</li>
<li><code>confirm</code>: número de notificações da doença (confirm) nessa data.</li>
</ul>
<p>Vamos usar o <code>{tidyr}</code> e o <code>{incidence2}</code> para isso:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cases_incidence <span class="ot">&lt;-</span> incidence2<span class="sc">::</span>covidregionaldataUK <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Pré-processar valores ausentes</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">replace_na</span>(base<span class="sc">::</span><span class="fu">list</span>(<span class="at">cases_new =</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calcular a incidência diária</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  incidence2<span class="sc">::</span><span class="fu">incidence</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_index =</span> <span class="st">"date"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">counts =</span> <span class="st">"cases_new"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">count_values_to =</span> <span class="st">"confirm"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_names_to =</span> <span class="st">"date"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">complete_dates =</span> <span class="cn">TRUE</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Com <code>incidence2::incidence()</code>, agregamos casos em diferentes <em>intervalos</em> de tempo (isto é, dias, semanas ou meses) ou por categorias de <em>grupo</em>. Além disso, podemos obter datas completas para todo o intervalo de datas por categoria de grupo usando <code>complete_dates = TRUE</code>. Explore mais tarde o <a href="https://www.reconverse.org/incidence2/manual.html#sec:man-incidence">manual de referência de <code>incidence2::incidence()</code></a>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Detalhes">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Detalhes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Podemos reproduzir o {incidence2} com o {dplyr}?</strong></p>
<p>Podemos obter um objeto semelhante a <code>cases</code> a partir do data frame <code>incidence2::covidregionaldataUK</code> usando o pacote <code>{dplyr}</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>incidence2<span class="sc">::</span>covidregionaldataUK <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(date, cases_new) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">confirm =</span> <span class="fu">sum</span>(cases_new, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">ungroup</span>()</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>No entanto, a função <code>incidence2::incidence()</code> contém argumentos convenientes, como <code>complete_dates</code>, que facilitam a obtenção de um objeto de incidência com o mesmo intervalo de datas para cada agrupamento, sem a necessidade de linhas de código extras ou de um pacote de séries temporais.</p>
</div>
</div>
</div>
<p>Vamos contextualizar este episódio no cenário de um <strong>surto em andamento</strong> com apenas os <strong>primeiros 90 dias</strong> de dados observados (escolhidos aqui para fins de ilustração, não como uma etapa obrigatória).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Supor que temos apenas os primeiros 90 dias desses dados</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cases_sliced <span class="ot">&lt;-</span> cases_incidence <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">90</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cases_sliced)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para passar as saídas do <code>{incidence2}</code> para o <code>{EpiNow2}</code>, precisamos remover uma coluna do objeto <code>cases_sliced</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remover coluna para atender ao formato de entrada do {EpiNow2}</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>cases <span class="ot">&lt;-</span> cases_sliced <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>count_variable)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>cases</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 90 × 2
   date       confirm
   &lt;date&gt;       &lt;dbl&gt;
 1 2020-01-30       3
 2 2020-01-31       0
 3 2020-02-01       0
 4 2020-02-02       0
 5 2020-02-03       0
 6 2020-02-04       0
 7 2020-02-05       2
 8 2020-02-06       0
 9 2020-02-07       0
10 2020-02-08       8
# ℹ 80 more rows</code></pre>
</div>
</div>
</section>
<section id="distribuições-de-atraso" class="level3">
<h3 class="anchored" data-anchor-id="distribuições-de-atraso">Distribuições de atraso</h3>
<p>Assumimos que existem atrasos desde o momento da infecção até o momento em que um caso é notificado. Especificamos esses atrasos como distribuições para levar em conta a incerteza nas diferenças em nível individual. O atraso pode envolver múltiplos tipos de processos. Um atraso típico desde o momento da infecção até a notificação do caso pode consistir em:</p>
<blockquote class="blockquote">
<p><strong>tempo da infecção até o início dos sintomas</strong> (o <a href="../glossario.html#incubation">período de incubação</a>) + <strong>tempo do início dos sintomas até a notificação do caso</strong> (o tempo de notificação).</p>
</blockquote>
<p>A distribuição de atraso para cada um desses processos pode ser estimada a partir de dados ou obtida da literatura. Podemos expressar a incerteza sobre os parâmetros corretos das distribuições assumindo que elas têm parâmetros <strong>fixos</strong> ou parâmetros <strong>variáveis</strong>. Para entender a diferença entre distribuições <strong>fixas</strong> e <strong>variáveis</strong>, vamos considerar o período de incubação.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Atrasos e dados
</div>
</div>
<div class="callout-body-container callout-body">
<p>O número e o tipo de atraso são entradas flexíveis que dependem dos dados. Os exemplos abaixo destacam como os atrasos podem ser especificados para diferentes fontes de dados:</p>
<center>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Fonte de dados</th>
<th>Atraso(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Momento do início dos sintomas</td>
<td>Período de incubação</td>
</tr>
<tr class="even">
<td>Momento da notificação do caso</td>
<td>Período de incubação + tempo do início dos sintomas até a notificação do caso</td>
</tr>
<tr class="odd">
<td>Momento da internação</td>
<td>Período de incubação + tempo do início dos sintomas até a internação</td>
</tr>
</tbody>
</table>
</center>
</div>
</div>
<section id="distribuição-do-período-de-incubação" class="level4">
<h4 class="anchored" data-anchor-id="distribuição-do-período-de-incubação">Distribuição do período de incubação</h4>
<p>A distribuição do período de incubação para muitas doenças geralmente pode ser obtida da literatura. O pacote <code>{epiparameter}</code> contém uma biblioteca de parâmetros epidemiológicos para diferentes doenças extraídos da literatura.</p>
<p>Especificamos uma distribuição gama (fixa) com média <span class="math inline">\(\mu = 4\)</span> e desvio-padrão <span class="math inline">\(\sigma = 2\)</span> (shape = <span class="math inline">\(4\)</span>, scale = <span class="math inline">\(1\)</span>) usando a função <code>Gamma()</code>, da seguinte forma:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>incubation_period_fixed <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">Gamma</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="dv">4</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="dv">2</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">max =</span> <span class="dv">20</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>incubation_period_fixed</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- gamma distribution (max: 20):
  shape:
    4
  rate:
    1</code></pre>
</div>
</div>
<p>Aqui você configura o período de incubação usando estatísticas resumo (<code>mean = 4</code>, <code>sd = 2</code>) como entrada, mas o <code>{EpiNow2}</code> converte esses valores nos parâmetros <code>shape</code> e <code>rate</code> de uma distribuição de probabilidade Gama e os imprime como saída. O argumento <code>max</code> é o valor máximo que a distribuição pode assumir; neste exemplo, 20 dias.</p>
<p>Podemos plotar as distribuições geradas pelo <code>{EpiNow2}</code> usando <code>plot()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(incubation_period_fixed)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Por que uma distribuição gama?
</div>
</div>
<div class="callout-body-container callout-body">
<p>O período de incubação deve ser um valor positivo. Portanto, devemos especificar uma distribuição no <code>{EpiNow2}</code> restrita apenas a valores positivos.</p>
<p><code>Gamma()</code> dá suporte a distribuições Gama e <code>LogNormal()</code> a distribuições Log-normal, que são distribuições exclusivas para valores positivos.</p>
<p>Para todos os tipos de atraso, precisaremos usar distribuições restritas a valores positivos — não queremos incluir atrasos com dias negativos em nossa análise!</p>
</div>
</div>
</section>
<section id="incluindo-a-incerteza-da-distribuição" class="level4">
<h4 class="anchored" data-anchor-id="incluindo-a-incerteza-da-distribuição">Incluindo a incerteza da distribuição</h4>
<p>Para especificar uma distribuição <strong>variável</strong>, incluímos incerteza em torno da média <span class="math inline">\(\mu\)</span> e do desvio-padrão <span class="math inline">\(\sigma\)</span> de nossa distribuição gama. Se a nossa distribuição do período de incubação tem média <span class="math inline">\(\mu\)</span> e desvio-padrão <span class="math inline">\(\sigma\)</span>, podemos assumir que a média (<span class="math inline">\(\mu\)</span>) segue uma distribuição Normal com desvio-padrão <span class="math inline">\(\sigma_{\mu}\)</span>:</p>
<p><span class="math display">\[\mbox{Normal}(\mu,\sigma_{\mu}^2)\]</span></p>
<p>e o desvio-padrão (<span class="math inline">\(\sigma\)</span>) segue uma distribuição Normal com desvio-padrão <span class="math inline">\(\sigma_{\sigma}\)</span>:</p>
<p><span class="math display">\[\mbox{Normal}(\sigma,\sigma_{\sigma}^2).\]</span></p>
<p>Especificamos isso usando <code>Normal()</code> para cada argumento: a média (<span class="math inline">\(\mu = 4\)</span> com <span class="math inline">\(\sigma_{\mu} = 0.5\)</span>) e o desvio-padrão (<span class="math inline">\(\sigma = 2\)</span> com <span class="math inline">\(\sigma_{\sigma} = 0.5\)</span>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>incubation_period_variable <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">Gamma</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> EpiNow2<span class="sc">::</span><span class="fu">Normal</span>(<span class="at">mean =</span> <span class="dv">4</span>, <span class="at">sd =</span> <span class="fl">0.5</span>),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> EpiNow2<span class="sc">::</span><span class="fu">Normal</span>(<span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="fl">0.5</span>),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">max =</span> <span class="dv">20</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>incubation_period_variable</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- gamma distribution (max: 20):
  shape:
    - normal distribution:
      mean:
        4
      sd:
        0.61
  rate:
    - normal distribution:
      mean:
        1
      sd:
        0.31</code></pre>
</div>
</div>
<p>Vamos plotar a distribuição que acabamos de configurar:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(incubation_period_variable)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Checklist">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Checklist
</div>
</div>
<div class="callout-body-container callout-body">
<p>Preferimos adicionar incerteza a cada estimativa pontual sempre que disponível. As boas práticas no relato de distribuições de atraso epidemiológicas recomendam incluir estimativas de incerteza, pois isso pode impactar a modelagem subsequente e sinalizar que mais dados são necessários (<a href="https://doi.org/10.1371/journal.pcbi.1012520">Charniga et al., 2024</a>).</p>
</div>
</div>
</section>
<section id="atrasos-de-notificação" class="level4">
<h4 class="anchored" data-anchor-id="atrasos-de-notificação">Atrasos de notificação</h4>
<p>Após o período de incubação, haverá um atraso de tempo adicional entre o início dos sintomas e a notificação do caso: o atraso de notificação. Podemos especificar isso como uma distribuição fixa ou variável, ou estimar uma distribuição a partir dos dados.</p>
<p>Ao especificar uma distribuição, é útil visualizar a densidade de probabilidade para observar o pico e a dispersão da distribuição; neste caso, usaremos uma distribuição <em>log-normal</em>.</p>
<p>Se quisermos assumir que o atraso médio de notificação é de 2 dias (com uma incerteza de 0,5 dia) e um desvio-padrão de 1 dia (com incerteza de 0,5 dia), podemos especificar uma distribuição variável usando <code>LogNormal()</code> como fizemos antes:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>reporting_delay_variable <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">LogNormal</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> EpiNow2<span class="sc">::</span><span class="fu">Normal</span>(<span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="fl">0.5</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> EpiNow2<span class="sc">::</span><span class="fu">Normal</span>(<span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd =</span> <span class="fl">0.5</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">max =</span> <span class="dv">10</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Detalhes">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Detalhes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Como obter o atraso de notificação a partir dos dados?</strong></p>
<p>Se houver dados disponíveis sobre o tempo entre o início dos sintomas e a notificação, podemos usar a função <code>EpiNow2::estimate_delay()</code> para estimar uma distribuição log-normal a partir de um vetor de atrasos.</p>
<p>O código abaixo ilustra como usar <code>EpiNow2::estimate_delay()</code> com dados sintéticos de ebola. Calculamos o atraso de notificação para cada caso como a diferença de tempo <strong>da</strong> data de início dos sintomas <strong>até</strong> a data de internação (data em que o caso foi notificado).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Etapas:</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># - obter dados de ebola do pacote {outbreaks}</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># - manter um subconjunto de colunas apenas para este exemplo</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># - calcular a diferença de tempo entre duas datas na linelist</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># - extrair a diferença de tempo como um objeto da classe vector</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># - estimar os parâmetros de atraso usando {EpiNow2}</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>outbreaks<span class="sc">::</span>ebola_sim_clean<span class="sc">$</span>linelist <span class="sc">%&gt;%</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(case_id, date_of_onset, date_of_hospitalisation) <span class="sc">%&gt;%</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">reporting_delay =</span> date_of_hospitalisation <span class="sc">-</span> date_of_onset) <span class="sc">%&gt;%</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">pull</span>(reporting_delay) <span class="sc">%&gt;%</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  EpiNow2<span class="sc">::</span><span class="fu">estimate_delay</span>(</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">samples =</span> <span class="dv">1000</span>,</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">bootstraps =</span> <span class="dv">10</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- lognormal distribution (max: 22):
  meanlog:
    - normal distribution:
      mean:
        0.23
      sd:
        0.11
  sdlog:
    - normal distribution:
      mean:
        0.96
      sd:
        0.099</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="tempo-de-geração" class="level4">
<h4 class="anchored" data-anchor-id="tempo-de-geração">Tempo de geração</h4>
<p>Como apresentamos no <a href="../episodios/01-acessar-atrasos.html">episódio anterior deste tutorial</a>, também precisamos especificar uma distribuição para o tempo de geração. Aqui usaremos uma distribuição log-normal com média de 3,6 e desvio-padrão de 3,1 (<a href="https://doi.org/10.2807/1560-7917.ES.2020.25.17.2000257">Ganyani et al.&nbsp;2020</a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>generation_time_variable <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">LogNormal</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> EpiNow2<span class="sc">::</span><span class="fu">Normal</span>(<span class="at">mean =</span> <span class="fl">3.6</span>, <span class="at">sd =</span> <span class="fl">0.5</span>),</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> EpiNow2<span class="sc">::</span><span class="fu">Normal</span>(<span class="at">mean =</span> <span class="fl">3.1</span>, <span class="at">sd =</span> <span class="fl">0.5</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">max =</span> <span class="dv">20</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Checklist">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Checklist
</div>
</div>
<div class="callout-body-container callout-body">
<p>Agora temos as distribuições necessárias para quantificar a transmissão a partir de notificações de casos usando o <code>{EpiNow2}</code>:</p>
<ul>
<li><strong>Tempo de geração</strong>: tempo entre o início da infecciosidade em um caso primário (índice) e em seu caso secundário.</li>
<li><strong>Atrasos</strong>: tempo da infecção até a notificação do caso (período de incubação + atraso de notificação).</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>generation_time_variable</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>incubation_period_variable</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>reporting_delay_variable</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Para se aprofundar">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Para se aprofundar
</div>
</div>
<div class="callout-body-container callout-body">
<p>Observe que podemos configurar estatísticas resumo (por exemplo, <code>mean</code>, <code>sd</code>) como entrada para <code>EpiNow2::LogNormal()</code> ou <code>EpiNow2::Gamma()</code>, mas o <code>{EpiNow2}</code> sempre as converterá para parâmetros da distribuição de probabilidade: <code>shape</code> e <code>scale</code> para Gamma, <code>meanlog</code> e <code>sdlog</code> para LogNormal.</p>
<p>Quando possível, preferimos especificar diretamente os parâmetros “naturais” da distribuição (como <code>shape</code> e <code>rate</code> para Gamma, <code>meanlog</code> e <code>sdlog</code> para LogNormal), em vez de depender da conversão média/desvio-padrão, pois isso evita ambiguidades e proporciona um controle mais preciso sobre a distribuição resultante.</p>
</div>
</div>
<div class="desafio callout callout-style-default callout-tip callout-titled" title="Desafio">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Desafio
</div>
</div>
<div class="callout-body-container callout-body">
<p>Usando o período de incubação do sarampo do pacote <code>{epiparameter}</code>, adapte essa saída à interface de distribuição do <code>{EpiNow2}</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>measles_incubation <span class="ot">&lt;-</span> epiparameter<span class="sc">::</span><span class="fu">epiparameter_db</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">disease =</span> <span class="st">"Measles"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">epi_name =</span> <span class="st">"incubation"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">single_epiparameter =</span> <span class="cn">TRUE</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Dica">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Dica
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Use estas perguntas como guia:</p>
<ul>
<li>O tempo de incubação segue uma distribuição LogNormal ou Gamma?</li>
<li>Quais são os <em>parâmetros da distribuição</em> do tempo de incubação?</li>
<li>Com base nessa distribuição, qual função devemos usar: <code>EpiNow2::LogNormal()</code> ou <code>EpiNow2::Gamma()</code>?</li>
<li>Qual poderia ser o número máximo de dias para essa distribuição? Observe isso a partir de um gráfico.</li>
</ul>
<p>Você pode copiar e colar os valores dos parâmetros correspondentes diretamente da saída do <code>{epiparameter}</code> na entrada do <code>{EpiNow2}</code>.</p>
</div>
</div>
</div>
<div class="solucao callout callout-style-default callout-note callout-titled" title="Solução">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solução
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Vamos imprimir a saída:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>measles_incubation</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Disease: Measles
Pathogen: Measles Virus
Epi Parameter: incubation period
Study: Lessler J, Reich N, Brookmeyer R, Perl T, Nelson K, Cummings D (2009).
"Incubation periods of acute respiratory viral infections: a systematic
review." _The Lancet Infectious Diseases_.
doi:10.1016/S1473-3099(09)70069-12
&lt;https://doi.org/10.1016/S1473-3099%2809%2970069-12&gt;.
Distribution: lnorm (days)
Parameters:
  meanlog: 2.526
  sdlog: 0.207</code></pre>
</div>
</div>
<p>Ela segue uma distribuição Log-normal (<code>lnorm</code>), com os parâmetros: <code>meanlog</code> e <code>sdlog</code>; portanto, a função correspondente é <code>EpiNow2::LogNormal()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(measles_incubation, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">25</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A partir do gráfico, um valor máximo plausível para o período de incubação seria de 20 dias.</p>
<p>Em seguida, nossa chamada da função do EpiNow2 fica assim:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>measles_incubation_epinow <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">LogNormal</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanlog =</span> <span class="fl">2.526</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sdlog =</span> <span class="fl">0.207</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">max =</span> <span class="dv">20</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>measles_incubation_epinow</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>- lognormal distribution (max: 20):
  meanlog:
    2.5
  sdlog:
    0.21</code></pre>
</div>
</div>
<p>Ou <code>epiparameter::get_parameters(measles_incubation)</code> para reutilizar os parâmetros diretamente.</p>
<p>O gráfico gerado pelo {EpiNow2} é:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(measles_incubation_epinow)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observe que se esquecermos de definir um valor máximo, obteremos um erro nesta etapa.</p>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="obtenção-das-estimativas" class="level2">
<h2 class="anchored" data-anchor-id="obtenção-das-estimativas">Obtenção das estimativas</h2>
<p>A função <code>epinow()</code> é um wrapper para a função <code>estimate_infections()</code>, usada para estimar casos por data de infecção. A distribuição do tempo de geração e as distribuições de atraso devem ser fornecidas usando as funções <code>generation_time_opts()</code> e <code>delay_opts()</code>, respectivamente.</p>
<p>Existem muitas outras entradas que podem ser passadas para <code>epinow()</code>; consulte <code>?EpiNow2::epinow()</code> para mais detalhes. Uma entrada opcional é especificar uma priori <em>log-normal</em> para o número de reprodução efetivo <span class="math inline">\(R_t\)</span> no início do surto. Especificamos uma média de 2 e desvio-padrão de 2 como argumentos de <code>prior</code> dentro de <code>rt_opts()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># definir a distribuição a priori de Rt</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>rt_prior <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">rt_opts</span>(<span class="at">prior =</span> EpiNow2<span class="sc">::</span><span class="fu">LogNormal</span>(<span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">2</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Inferência bayesiana usando o Stan
</div>
</div>
<div class="callout-body-container callout-body">
<p>A inferência bayesiana é realizada usando métodos MCMC com o programa <a href="https://mc-stan.org/">Stan</a>. Há uma série de configurações padrão para as funções do Stan, incluindo o número de cadeias e o número de amostras por cadeia (veja <code>?EpiNow2::stan_opts()</code>).</p>
<p>Para reduzir o tempo de computação, podemos executar as cadeias em paralelo. Para fazer isso, devemos definir o número de núcleos a serem utilizados. Por padrão, 4 cadeias MCMC são executadas (veja <code>EpiNow2::stan_opts()$chains</code>), de modo que podemos definir um número igual de núcleos para serem usados em paralelo da seguinte forma:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>withr<span class="sc">::</span><span class="fu">local_options</span>(base<span class="sc">::</span><span class="fu">list</span>(<span class="at">mc.cores =</span> <span class="dv">4</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Para descobrir o número máximo de núcleos disponíveis na sua máquina, use <code>parallel::detectCores()</code>. Se tiver menos de 4, você pode substituir <code>mc.cores = 4</code> por <code>mc.cores = parallel::detectCores() - 1</code>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Checklist">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Checklist
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Nota:</strong> no código abaixo, são usadas as distribuições <code>*_fixed</code> em vez de <code>*_variable</code> (distribuições de atraso com incerteza). Isso serve para acelerar o tempo de computação. De modo geral, recomenda-se usar distribuições variáveis que levem em conta a incerteza adicional.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># alternativas fixas</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>generation_time_fixed <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">LogNormal</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="fl">3.6</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="fl">3.1</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">max =</span> <span class="dv">20</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>reporting_delay_fixed <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">LogNormal</span>(</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="dv">2</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="dv">1</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">max =</span> <span class="dv">10</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>Agora você está pronto para executar <code>EpiNow2::epinow()</code> para estimar o número de reprodução variante no tempo para os primeiros 90 dias:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>estimates <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">epinow</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># casos notificados</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> cases,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># atrasos</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">generation_time =</span> EpiNow2<span class="sc">::</span><span class="fu">generation_time_opts</span>(generation_time_fixed),</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">delays =</span> EpiNow2<span class="sc">::</span><span class="fu">delay_opts</span>(incubation_period_fixed <span class="sc">+</span> reporting_delay_fixed),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># priori</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">rt =</span> rt_prior</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<!-- ```{r, message = FALSE,warning=FALSE, eval = TRUE, echo=FALSE} -->
<!-- estimates <- EpiNow2::epinow( -->
<!--   # reported cases -->
<!--   data = cases, -->
<!--   # delays -->
<!--   generation_time = EpiNow2::generation_time_opts(generation_time_fixed), -->
<!--   delays = EpiNow2::delay_opts(incubation_period_fixed + reporting_delay_fixed), -->
<!--   # prior -->
<!--   rt = rt_prior, -->
<!--   stan = EpiNow2::stan_opts(method = "vb") -->
<!-- ) -->
<!-- ``` -->
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Não espere a conclusão disto para continuar
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para o propósito deste tutorial, podemos opcionalmente usar <code>EpiNow2::stan_opts()</code> para reduzir o tempo de computação. Podemos especificar um número fixo de <code>samples = 1000</code> e <code>chains = 2</code> no argumento <code>stan</code> da função <code>EpiNow2::epinow()</code>. Esperamos que isso leve aproximadamente 3 minutos.</p>
<!-- We can optionally set `stan = stan_opts(method = "vb")` to use an approximate sampling method. We expect this to take less than 1 minute. -->
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># você pode adicionar o argumento `stan`</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>EpiNow2<span class="sc">::</span><span class="fu">epinow</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  ...,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">stan =</span> EpiNow2<span class="sc">::</span><span class="fu">stan_opts</span>(<span class="at">samples =</span> <span class="dv">1000</span>, <span class="at">chains =</span> <span class="dv">2</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Lembre-se:</strong> usar um número adequado de <em>samples</em> (amostras) e <em>chains</em> (cadeias) é crucial para garantir a convergência e obter estimativas confiáveis em computações bayesianas usando o Stan. Saídas mais precisas têm como contrapartida um tempo de processamento maior.</p>
</div>
</div>
<section id="resultados" class="level3">
<h3 class="anchored" data-anchor-id="resultados">Resultados</h3>
<p>Podemos extrair e visualizar as estimativas do número de reprodução efetivo ao longo do tempo:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(estimates, <span class="at">type =</span> <span class="st">"R"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A incerteza nas estimativas aumenta ao longo do tempo. Isso ocorre porque as estimativas são orientadas por dados do passado — dentro dos períodos de atraso.</p>
<p>O gráfico distingue três categorias:</p>
<ul>
<li><strong>Estimate</strong> (verde) usa todos os dados disponíveis;</li>
<li><strong>Estimate based on partial data</strong> (laranja) baseia-se em menos dados (porque as infecções em torno desse período têm maior probabilidade de ainda não terem sido observadas) e, portanto, apresenta intervalos progressivamente mais amplos em direção à data do último ponto de dados; e</li>
<li><strong>Forecast</strong> (roxo) é uma projeção para o futuro.</li>
</ul>
<p>Também podemos visualizar a estimativa da taxa de crescimento ao longo do tempo:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(estimates, <span class="at">type =</span> <span class="st">"growth_rate"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-quantificar-transmissibilidade_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para extrair um resumo das principais métricas de transmissão na <em>data mais recente</em> dos dados:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(estimates)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        measure              estimate
                         &lt;char&gt;                &lt;char&gt;
1:       New infections per day 9094 (4896 -- 122233)
2:   Expected change in reports                Stable
3:   Effective reproduction no.       1 (0.76 -- 1.4)
4:               Rate of growth  0.01 (-0.095 -- 0.1)
5: Doubling/halving time (days)      69 (6.6 -- -7.3)</code></pre>
</div>
</div>
<p>Como essas estimativas são baseadas em dados parciais, elas têm um amplo intervalo de incerteza.</p>
<ul>
<li><p>A partir do resumo de nossa análise, vemos que a mudança esperada nas notificações é Stable com novas infecções estimadas em 9094 (4896 – 122233).</p></li>
<li><p>A estimativa do número de reprodução efetivo <span class="math inline">\(R_t\)</span> (na última data dos dados) é 1 (0.76 – 1.4).</p></li>
<li><p>A taxa de crescimento exponencial do número de casos é 0.01 (-0.095 – 0.1).</p></li>
<li><p>O tempo de duplicação (o tempo necessário para o número de casos dobrar) é 69 (6.6 – -7.3).</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span><code>Expected change in reports</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Um fator que descreve a mudança esperada nas notificações com base na probabilidade a posteriori de que <span class="math inline">\(R_t &lt; 1\)</span>.</p>
<center>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Probabilidade (<span class="math inline">\(p\)</span>)</th>
<th>Mudança esperada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p &lt; 0.05\)</span></td>
<td>Aumentando (<em>Increasing</em>)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.05 \leq p&lt; 0.4\)</span></td>
<td>Provavelmente aumentando (<em>Likely increasing</em>)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0.4 \leq p&lt; 0.6\)</span></td>
<td>Estável (<em>Stable</em>)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.6 \leq p &lt; 0.95\)</span></td>
<td>Provavelmente diminuindo (<em>Likely decreasing</em>)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0.95 \leq p \leq 1\)</span></td>
<td>Diminuindo (<em>Decreasing</em>)</td>
</tr>
</tbody>
</table>
</center>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Intervalos de credibilidade
</div>
</div>
<div class="callout-body-container callout-body">
<p>Em todas as figuras de saída do <code>{EpiNow2}</code>, as regiões sombreadas refletem intervalos de credibilidade de 90%, 50% e 20%, ordenados do mais claro ao mais escuro.</p>
</div>
</div>
<div class="desafio callout callout-style-default callout-tip callout-titled" title="Desafio">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Desafio
</div>
</div>
<div class="callout-body-container callout-body">
<p>Na saída de <code>plot(estimates, type = "R")</code>, qual parâmetro de entrada delimita a extensão da trajetória com a categoria <code>Estimate based on parial data</code> (laranja)?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Dica">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Dica
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Como explicamos acima, as infecções em torno desse período têm maior probabilidade de ainda não terem sido observadas. Portanto, o parâmetro de entrada deve informar a probabilidade de observar novas infecções.</p>
</div>
</div>
</div>
<div class="solucao callout callout-style-default callout-note callout-titled" title="Solução">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solução
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>O valor máximo finito da distribuição do <em>tempo de geração</em> define o intervalo de <code>Estimate based on parial data</code>. O <em>tempo de geração</em> foi configurado com um valor máximo de 20 dias.</p>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Checklist">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Checklist
</div>
</div>
<div class="callout-body-container callout-body">
<p>O <code>{EpiNow2}</code> pode ser usado para estimar métricas de transmissão a partir de dados de casos em qualquer momento durante o curso de um surto. A confiabilidade dessas estimativas depende da qualidade dos dados e da escolha apropriada das distribuições de atraso.</p>
<p>Para reutilizar diretamente os atrasos armazenados no <code>{epiparameter}</code>, leia o próximo tutorial sobre <a href="../episodios/03-funcoes-de-atraso.html">usar distribuições de atraso na análise</a>.</p>
<p>Para aprender a criar previsões e explorar algumas das opções adicionais de inferência disponíveis no <code>{EpiNow2}</code>, leia o tutorial seguinte sobre <a href="../episodios/04-criar-previsoes.html">criar previsões de curto prazo</a>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Discussão">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Discussão
</div>
</div>
<section id="como-o-epinow2-funciona" class="level3 callout-body-container callout-body">
<h3 class="anchored" data-anchor-id="como-o-epinow2-funciona">Como o {EpiNow2} funciona?</h3>
<p>O {EpiNow2} contém diferentes modelos sobre como as infecções surgem. Um dos principais modelos usados na configuração padrão é o <strong>modelo da equação de renovação</strong>. Se você quiser se familiarizar com ele e aprender como os atrasos são levados em conta na estimativa de <span class="math inline">\(R_t\)</span>, você pode ler o episódio sobre <a href="../notas/equacao-de-renovacao.html">Introdução à equação de renovação</a> na seção “Mais recursos” do site deste tutorial.</p>
</section>
</div>
</section>
</section>
<section id="desafio" class="level2">
<h2 class="anchored" data-anchor-id="desafio">Desafio</h2>
<div class="desafio callout callout-style-default callout-tip callout-titled" title="Desafio">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Desafio
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Quantificar a heterogeneidade geográfica</strong></p>
<p>Os dados de surto do início da pandemia de COVID-19 no Reino Unido provenientes do pacote R <code>{incidence2}</code> incluem a região em que os casos foram registrados. Para encontrar estimativas regionais do número de reprodução efetivo e de casos, devemos formatar os dados para que tenham três colunas:</p>
<ul>
<li><code>date</code>: a data,</li>
<li><code>region</code>: a região,</li>
<li><code>confirm</code>: número de notificações da doença (confirm) para uma região em uma determinada data.</li>
</ul>
<p>Gere estimativas regionais de Rt a partir do data frame <code>incidence2::covidregionaldataUK</code>:</p>
<ul>
<li>use o <code>{incidence2}</code> para converter os dados agregados em dados de incidência pela variável <code>region</code>,</li>
<li>mantenha as primeiras 90 datas para todas as regiões,</li>
<li>estime o Rt por região usando o tempo de geração e os atrasos definidos neste episódio.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>regional_cases <span class="ot">&lt;-</span> incidence2<span class="sc">::</span>covidregionaldataUK <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># usar o {tidyr} para pré-processar valores ausentes</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">replace_na</span>(base<span class="sc">::</span><span class="fu">list</span>(<span class="at">cases_new =</span> <span class="dv">0</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Dica">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Dica
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Para manipular os dados, você pode:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>regional_cases <span class="ot">&lt;-</span> incidence2<span class="sc">::</span>covidregionaldataUK <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># usar o {tidyr} para pré-processar valores ausentes</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">replace_na</span>(base<span class="sc">::</span><span class="fu">list</span>(<span class="at">cases_new =</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># usar o {incidence2} para converter dados agregados em dados de incidência</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  incidence2<span class="sc">::</span><span class="fu">incidence</span>(</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_index =</span> <span class="st">"date"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">groups =</span> <span class="st">"region"</span>,</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">counts =</span> <span class="st">"cases_new"</span>,</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">count_values_to =</span> <span class="st">"confirm"</span>,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_names_to =</span> <span class="st">"date"</span>,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">complete_dates =</span> <span class="cn">TRUE</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>count_variable) <span class="sc">%&gt;%</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(date <span class="sc">&lt;</span> <span class="fu">ymd</span>(<span class="dv">20200301</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Para aprender como realizar a estimação regional de Rt, leia a seção sobre <code>regional_epinow()</code> na vinheta Get started em <a href="https://epiforecasts.io/EpiNow2/articles/EpiNow2.html#regional_epinow" class="uri">https://epiforecasts.io/EpiNow2/articles/EpiNow2.html#regional_epinow</a></p>
</div>
</div>
</div>
<div class="solucao callout callout-style-default callout-note callout-titled" title="Solução">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solução
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Para encontrar estimativas regionais, usamos as mesmas entradas de <code>epinow()</code> na função <code>regional_epinow()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>estimates_regional <span class="ot">&lt;-</span> EpiNow2<span class="sc">::</span><span class="fu">regional_epinow</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># casos</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> regional_cases,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># atrasos</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">generation_time =</span> EpiNow2<span class="sc">::</span><span class="fu">generation_time_opts</span>(generation_time_fixed),</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">delays =</span> EpiNow2<span class="sc">::</span><span class="fu">delay_opts</span>(incubation_period_fixed <span class="sc">+</span> reporting_delay_fixed),</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># priori</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">rt =</span> rt_prior</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Plote os resultados com:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>estimates_regional<span class="sc">$</span>summary<span class="sc">$</span>summarised_results<span class="sc">$</span>table</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>estimates_regional<span class="sc">$</span>summary<span class="sc">$</span>plots<span class="sc">$</span>R</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><img src="../img/quantify-transmissibility-regional.png" class="img-fluid"></p>
</div>
</div>
</div>
</div>
</div>
<!-- :::::::::::::::::::::::::: testimonial -->
<!-- ### the i2extras package -->
<!-- `{i2extras}` package also estimate transmission metrics like growth rate and doubling/halving time at different time intervals (i.e., days, weeks, or months). `{i2extras}` require `{incidence2}` objects as inputs. Read further in its [Fitting curves](https://www.reconverse.org/i2extras/articles/fitting_epicurves.html) vignette. -->
<!-- :::::::::::::::::::::::::: -->
<div class="callout callout-style-default callout-note callout-titled" title="Pontos-chave">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Pontos-chave
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Métricas de transmissão podem ser estimadas a partir de dados de casos após levar em conta os atrasos</li>
<li>A incerteza pode ser incorporada nas distribuições de atraso</li>
</ul>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../episodios/01-acessar-atrasos.html" class="pagination-link" aria-label="Acessar distribuições de atraso epidemiológicas">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Acessar distribuições de atraso epidemiológicas</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../episodios/03-funcoes-de-atraso.html" class="pagination-link" aria-label="Usar distribuições de atraso na análise">
        <span class="nav-page-text"><span class="chapter-title">Usar distribuições de atraso na análise</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Baseado em Epiverse-TRACE <em>Tutorials Middle</em> (CC-BY 4.0)</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/MVMLima/tutorials-middle-pt/edit/main/episodios/02-quantificar-transmissibilidade.qmd" class="toc-action"><i class="bi bi-github"></i>Editar essa página</a></li><li><a href="https://github.com/MVMLima/tutorials-middle-pt/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Adaptação PT-BR: Marcos V. M. de Lima</p>
</div>
  </div>
</footer>




</body></html>